import type { BackgroundTables } from "./types";

export const acolyte: BackgroundTables = {
  garment: [
    "a hooded temple robe",
    "plain grey vestments",
    "a white surplice over a wool habit",
    "a pilgrim's cloak stitched with holy symbols",
    "a simple cassock",
    "a novice's undyed tunic",
    "a ceremonial stole over travelling clothes",
    "a monk's rope-belted habit",
    "a sun-yellow robe of a dawn order",
    "a black mourning robe of a death god's temple",
  ],
  accessory: [
    "a prayer cord wound around one wrist",
    "a wooden holy symbol on a leather thong",
    "a small censer that still smells of incense",
    "candle wax spattered on the sleeves",
    "a well-thumbed book of hymns",
    "a shaved patch at the crown of the head",
    "a vial of holy water at the belt",
    "a pilgrim's badge from a distant shrine",
    "prayer beads worn smooth",
    "ash smudged on the forehead",
  ],
  wants: [
    "{They} needs to return a borrowed relic to the temple {deadline}, and has misplaced it.",
    "{They} wants to find out why the temple bells rang on their own {timeAgo}.",
    "{They} is collecting alms for a roof repair and is badly short of the total.",
    "{They} wants a sign from {their} god, and is starting to accept anything as one.",
    "{They} must deliver a blessing to {relation} {deadline}, but the road passes {place}.",
    "{They} wants to confess something to a priest who doesn't know {them}.",
    "{They} wants to bring {relation} back to the faith, willing or not.",
    "{They} needs volunteers to clean the shrine at {place} {deadline}.",
    "{They} wants to know who has been stealing candles from the chapel.",
    "{They} is on a pilgrimage and has, embarrassingly, lost the way.",
    "{They} wants to copy a holy text that the high priest keeps locked away.",
    "{They} needs someone to sit vigil with a dying stranger tonight.",
  ],
  quirks: [
    "blesses food, doors and occasionally people without asking",
    "quotes scripture at the worst possible moments",
    "prays out loud before every minor decision",
    "fasts on the oddest holy days, and mentions it",
  ],
  fears: ["that {their} god stopped listening {timeAgo}", "losing {their} faith in front of others", "heretics, and how persuasive they can be", "dying unshriven"],
  secrets: [
    "{They} stole the offering box once to feed {their} family.",
    "{They} isn't sure {their} god exists, and preaches anyway.",
    "{They} was sent to the temple as punishment, not by choice.",
    "{They} has been receiving visions, and they are not from {their} god.",
  ],
};
