import type { BackgroundTables } from "./types";

export const artisan: BackgroundTables = {
  garment: [
    "a leather work apron over a rolled-sleeve shirt",
    "a sturdy smock dusted with sawdust",
    "a guild tabard with a faded crest",
    "a canvas coat with burn marks on the cuffs",
    "a plain tunic stained with dye",
    "a potter's clay-streaked overshirt",
    "a weaver's bright woollen vest",
    "a glassblower's scorched leather jerkin",
    "a cobbler's sturdy trousers with patched knees",
    "a jeweller's fine but plain doublet",
  ],
  accessory: [
    "a belt of small tools",
    "callused, paint-stained hands",
    "a pencil tucked behind one ear",
    "a measuring cord looped at the hip",
    "a jeweller's loupe on a chain",
    "a guild token pinned at the collar",
    "a bandaged thumb",
    "wood shavings caught in the hair",
    "a sample of {their} work worn proudly",
    "thick leather gloves tucked into the belt",
  ],
  wants: [
    "{They} promised a masterpiece to {relation} {deadline} and has barely started it.",
    "{They} wants to find a rare material that only turns up near {place}.",
    "{They} needs a guild seal renewed {deadline}, and the guildmaster hates {them}.",
    "{They} wants to prove a rival copied {their} design.",
    "{They} lent {their} best tools to {relation} {timeAgo} and wants them back {deadline}.",
    "{They} wants someone, anyone, to finally pay for the last commission.",
    "{They} needs an apprentice who won't break everything {deadline}.",
    "{They} wants to enter the craft fair and win, for once.",
    "{They} wants to find out who keeps buying all of {their} work and why.",
    "{They} needs a new workshop after {their} landlord doubled the rent.",
    "{They} wants a noble to wear {their} work in public.",
    "{They} wants to recreate a lost technique {they} read about {timeAgo}.",
  ],
  quirks: [
    "judges every chair {they} sits on",
    "can't stop fixing things that aren't broken",
    "runs {their} fingers over every surface to feel the grain",
    "signs {their} work in a place nobody will ever look",
  ],
  fears: ["losing the use of {their} hands", "dying before making one truly great piece", "the new workshop down the road", "a client who knows exactly what they want"],
  secrets: [
    "{Their} most famous work was made by an apprentice.",
    "{They} forged a guild mark to get {their} first commission.",
    "{They} hides a flaw in every piece, on purpose.",
    "{They} once made a key for a burglar, and knew it.",
  ],
};
