import type { BackgroundTables } from "./types";

export const charlatan: BackgroundTables = {
  garment: [
    "a slightly too flashy doublet",
    "a velvet coat with fake gold buttons",
    "a borrowed noble's cloak",
    "a pedlar's patched motley",
    "a respectable merchant's outfit that fits a little oddly",
    "a fortune-teller's beaded shawl",
    "a priest's robe that {they} has no right to wear",
    "a dashing cape with a lining of cheap silk",
    "a physician's dark coat, minus the training",
    "a sober clerk's outfit, for looking trustworthy",
  ],
  accessory: [
    "a ring that turns fingers green",
    "a deck of marked cards",
    "a vial of 'miracle tonic'",
    "a forged letter of introduction",
    "three different names stitched inside the collar",
    "a dazzling false smile",
    "a monocle with plain glass",
    "a crystal ball wrapped in silk",
    "a sheaf of very official-looking papers",
    "a wig, slightly askew",
  ],
  wants: [
    "{They} needs to leave town {deadline}, because {relation} has started asking questions.",
    "{They} wants to sell one last batch of miracle tonic before anyone tests it.",
    "{They} wants to win back {item} from a card game {they} lost {timeAgo}.",
    "{They} is looking for a partner for one big, honest-looking scheme.",
    "{They} wants a new identity {deadline}, and has a few candidates in mind.",
    "{They} wants to find the swindler who swindled {them}, out of professional pride.",
    "{They} wants to marry into money {deadline}, and is auditioning candidates.",
    "{They} needs someone to play {their} long-lost sibling for one evening.",
    "{They} wants to sell the deed to {place}, which {they} does not own.",
    "{They} needs a convincing fake relic {deadline}.",
    "{They} wants to retire, just as soon as this one last job pays off.",
    "{They} wants to get back into the good graces of {relation}, whom {they} cheated.",
  ],
  quirks: ["answers every question with another question", "changes accent mid-sentence", "compliments everyone, generously and constantly", "keeps {their} hands where everyone can see them, a little too deliberately"],
  fears: ["meeting someone {they} conned", "honest work", "a town where everyone knows everyone", "being believed when {they} finally tells the truth"],
  secrets: [
    "{They} genuinely believes the tonic works.",
    "{They} is wanted under four different names.",
    "{They} gives most of what {they} steals to an orphanage.",
    "{Their} 'fake' fortune-telling has been eerily accurate lately.",
  ],
};
