import type { BackgroundTables } from "./types";

export const criminal: BackgroundTables = {
  garment: [
    "a dark hooded coat",
    "patched trousers and soft-soled boots",
    "a stolen gentleman's waistcoat",
    "a scarf worn high over the face",
    "a plain shirt with many hidden pockets",
    "a dock worker's rough jacket",
    "a black leather jerkin, oiled to stay quiet",
    "a servant's livery, borrowed without asking",
    "a grey cloak that blends into any crowd",
    "fine clothes with the tailor's labels cut out",
  ],
  accessory: [
    "a small knife up one sleeve",
    "a ring of lockpicks",
    "a scar across the knuckles",
    "a gang tattoo on the wrist",
    "eyes that keep checking the exits",
    "a broken nose that healed crooked",
    "a coil of thin rope under the coat",
    "a purse that clearly belongs to someone else",
    "a missing fingertip",
    "a brand on the shoulder, half hidden",
  ],
  wants: [
    "{They} owes {relation} for a job gone wrong and needs the money {deadline}.",
    "{They} wants to recover {item}, which {they} hid at {place} {timeAgo}.",
    "{They} wants out of the gang, alive.",
    "{They} needs an alibi for last night, {deadline}.",
    "{They} wants to find out who informed on {them} {timeAgo}.",
    "{They} is planning one last job and needs one more pair of hands.",
    "{They} needs a safe place to lie low {deadline}.",
    "{They} wants to break {relation} out of jail.",
    "{They} wants to fence {item} without the guild taking its cut.",
    "{They} needs a fake travel pass {deadline}.",
    "{They} wants revenge on the fence who cheated {them}.",
    "{They} wants to go straight, and has no idea how.",
  ],
  quirks: ["always pays in exact change", "knows every guard's shift by heart", "counts the doors in every room {they} enters", "never gives the same name twice"],
  fears: ["prison", "{their} old crew finding {them}", "the gallows at {place}", "the guild's enforcer"],
  secrets: [
    "{They} works for the city watch as an informant.",
    "{They} never actually killed anyone, despite the rumours {they} started.",
    "{They} is the one who robbed {relation}, and now pretends to help find the thief.",
    "{They} is the child of a magistrate.",
  ],
};
