import type { BackgroundTables } from "./types";

export const entertainer: BackgroundTables = {
  garment: [
    "a bright patchwork costume",
    "a feathered hat and a colourful cape",
    "a performer's silk shirt, laced loosely",
    "a jester's coat with bells removed",
    "a stage gown gone threadbare at the hem",
    "an acrobat's tight-fitting leathers",
    "a storyteller's long coat embroidered with stars",
    "a dancer's flowing skirts over sturdy boots",
    "a minstrel's doublet in two clashing colours",
    "a stage villain's black cloak, worn offstage too",
  ],
  accessory: [
    "a lute with one string missing",
    "theatrical makeup not quite washed off",
    "a juggling pouch at the hip",
    "a battered tambourine",
    "a fan of handbills for tonight's show",
    "a tin whistle tucked in the belt",
    "a mask hanging from a cord",
    "glitter that refuses to come off",
    "a flower pinned to the lapel, slightly wilted",
    "a pair of lucky dice that are never used",
  ],
  wants: [
    "{They} needs a crowd {deadline}, or the troupe goes hungry.",
    "{They} wants to perform for a noble and is willing to lie about {their} talents to do it.",
    "{They} wants to find the rival who stole {their} best song.",
    "{They} lent {their} costume trunk to {relation} {timeAgo} and needs it back {deadline}.",
    "{They} wants someone to write {them} a new act, because the old one is getting heckled.",
    "{They} is looking for a new partner after the last one ran off with the takings.",
    "{They} wants a true story to turn into a ballad, the more dangerous the better.",
    "{They} needs a venue {deadline}, since the last one burned down.",
    "{They} wants to find out who keeps throwing cabbages at {their} shows.",
    "{They} wants to win the bards' contest at {place}.",
    "{They} wants to get a song about {relation} banned before word of it spreads.",
    "{They} wants to retire from the stage and hasn't told the troupe.",
  ],
  quirks: ["narrates {their} own life in rhyme", "bows after finishing any sentence {they} is proud of", "can't walk past an audience without performing", "hums {their} own entrance music"],
  fears: ["an empty audience", "forgetting the words on stage", "a critic who once mocked {them}", "being ordinary"],
  secrets: [
    "{They} can't actually read music.",
    "{They} is a disinherited noble hiding in plain sight.",
    "{They} carries messages for a spy network hidden in {their} songs.",
    "{Their} most famous song was written by someone who died poor.",
  ],
};
