import type { BackgroundTables } from "./types";

export const farmer: BackgroundTables = {
  garment: [
    "a straw hat and a sweat-stained shirt",
    "sturdy boots caked in mud",
    "a homespun smock with patched knees",
    "an oilskin coat",
    "a wool vest over rolled sleeves",
    "dungarees held up with twine",
    "a shepherd's heavy hooded cloak",
    "a linen shirt bleached by the sun",
    "a sheepskin jacket",
    "a market-day best coat, slightly too tight",
  ],
  accessory: [
    "a sunburnt neck",
    "a pitchfork leaned against one shoulder",
    "seeds rattling in a pocket",
    "a pouch of pipe tobacco",
    "a handkerchief knotted at the throat",
    "straw caught in the hair",
    "a basket of eggs, carefully held",
    "a shepherd's crook",
    "dirt under every fingernail",
    "a sheepdog that follows everywhere",
  ],
  wants: [
    "{They} lost a prize goat near {place} and wants it back {deadline}.",
    "{They} needs help bringing in the harvest {deadline}.",
    "{They} wants to know what is trampling {their} fields at night.",
    "{They} lent {their} plough horse to {relation} {timeAgo} and needs it back {deadline}.",
    "{They} wants a fair price for {their} crop, for once.",
    "{They} wants to marry off a child and is interviewing anyone who passes.",
    "{They} wants to win the giant marrow contest at the fair.",
    "{They} needs rain {deadline}, and will pay anyone who can make it happen.",
    "{They} wants to know why the cows stopped giving milk {timeAgo}.",
    "{They} wants {relation} to stop letting pigs into {their} orchard.",
    "{They} needs a cure for a sickness spreading through the flock.",
    "{They} wants to see the capital once before {they} dies.",
  ],
  quirks: ["predicts the weather and is usually wrong", "talks to {their} crops by name", "wakes before the rooster and resents it", "judges people by the state of their boots"],
  fears: ["a bad harvest", "the thing in the old well", "locusts", "the landlord's steward"],
  secrets: [
    "{They} found a strange stone in the field and hasn't told anyone.",
    "{They} moved the boundary stones one night.",
    "{They} feeds a creature in the woods every night so it leaves the flock alone.",
    "{They} is the true heir to the land {they} rents.",
  ],
};
