import type { BackgroundTables } from "./types";

export const guard: BackgroundTables = {
  garment: [
    "a dented breastplate over a padded jack",
    "a city watch tabard",
    "a chainmail shirt under a heavy cloak",
    "a leather cuirass with polished buckles",
    "a uniform worn slightly too tight",
    "a gate warden's long blue coat",
    "a private house guard's livery",
    "an off-duty shirt that still looks like a uniform",
    "a caravan guard's mismatched armour",
    "a ceremonial palace tabard, rather faded",
  ],
  accessory: [
    "a club hanging from the belt",
    "a whistle on a cord",
    "a ring of heavy keys",
    "a scarred helmet tucked under one arm",
    "a lantern for the night watch",
    "a halberd that has seen better days",
    "a notebook of suspicious faces",
    "a badge polished to a shine",
    "a pair of iron manacles",
    "a flask that is definitely not water",
  ],
  wants: [
    "{They} needs to find an escaped prisoner {deadline}, before the captain notices.",
    "{They} wants a transfer away from the gate at {place}.",
    "{They} wants proof that {relation} is smuggling goods.",
    "{They} misplaced the prison keys {timeAgo} and needs them back {deadline}.",
    "{They} wants a promotion, and is happy to catch someone important to earn it.",
    "{They} wants one quiet shift, just one.",
    "{They} wants to know who has been leaving strange marks on the gate at night.",
    "{They} needs someone to cover {their} shift {deadline}.",
    "{They} wants to find the thief who stole {their} sword while {they} was on duty.",
    "{They} wants to catch the cutpurse who keeps working {their} street.",
    "{They} wants to prove {relation} innocent of a crime {they} witnessed.",
    "{They} wants the back pay the city has owed {them} since {timeAgo}.",
  ],
  quirks: ["challenges everyone with 'halt, who goes there' out of habit", "keeps a tally of every arrest", "stands at attention without noticing", "checks every lock {they} passes"],
  fears: ["being blamed for something {they} didn't do", "the riot that is surely coming", "the dark alleys of {place}", "the captain's temper"],
  secrets: [
    "{They} takes bribes, small ones, regularly.",
    "{They} let a prisoner go {timeAgo} out of pity.",
    "{They} slept through the night the vault was robbed.",
    "{They} is related to the most wanted thief in the city.",
  ],
};
