import type { BackgroundTables } from "./types";

export const guide: BackgroundTables = {
  garment: [
    "a weathered ranger's cloak",
    "a fur-lined hood",
    "boots worn soft from walking",
    "a hide coat with fringed sleeves",
    "layers of muted greens and browns",
    "a waxed cape that sheds the rain",
    "a mountaineer's quilted jacket",
    "a desert wrap against the sun and sand",
    "a tunic with leaves sewn in for cover",
    "a trapper's patched buckskins",
  ],
  accessory: [
    "a coil of rope over one shoulder",
    "a hand-drawn map tucked into the belt",
    "a walking staff carved with notches",
    "a hunting horn",
    "burrs stuck all over the hem",
    "a compass on a leather cord",
    "a hawk feather in the hat",
    "a sling and a pouch of stones",
    "a waterskin that never seems full",
    "a necklace of animal teeth",
  ],
  wants: [
    "{They} needs travellers to guide {deadline}, and is not picky.",
    "{They} wants to find the lost trail past {place}.",
    "{They} lost a client in the woods {timeAgo} and wants to find out what happened.",
    "{They} wants to map an area nobody has returned from.",
    "{They} lent {their} best map to {relation} {timeAgo} and wants it back {deadline}.",
    "{They} wants to retire somewhere with roofs.",
    "{They} wants to track down the beast that has been killing the deer near {place}.",
    "{They} needs to cross the pass {deadline}, before the snow closes it.",
    "{They} wants an escort through the bandit country, ironically.",
    "{They} wants to prove the old road is still safe, to win a bet.",
    "{They} wants to find the source of the strange lights over the hills.",
    "{They} wants to teach someone the trails before {their} knees give out.",
  ],
  quirks: ["smells the air before every decision", "refuses to sleep indoors", "reads animal tracks out loud like gossip", "gives directions using trees nobody else can tell apart"],
  fears: ["getting lost, which {they} would never admit", "whatever moves through the forest at night", "wolves that walk on two legs", "a client who won't listen"],
  secrets: [
    "{They} has never actually been to half the places {they} claims to know.",
    "{They} once led a group into an ambush for money.",
    "{They} knows a hidden way into the city that nobody else does.",
    "{They} has made a pact with the spirits of the forest.",
  ],
};
