import type { BackgroundTables } from "./types";

export const hermit: BackgroundTables = {
  garment: [
    "a patched robe of undyed wool",
    "furs stitched together by hand",
    "a rough sackcloth tunic",
    "a ragged cloak of many colours, all faded",
    "a robe with herbs pinned into the seams",
    "a cloak of woven reeds",
    "a monk's habit, decades old",
    "layers of moth-eaten blankets",
    "a moss-green shawl that might be actual moss",
    "a fine coat from another life, now in tatters",
  ],
  accessory: [
    "dirt under every fingernail",
    "a gnarled staff",
    "a bundle of dried herbs",
    "a necklace of small bones",
    "a pet crow that rarely leaves",
    "bare, calloused feet",
    "a clay pipe that is never lit",
    "a satchel of strange mushrooms",
    "a walking stick hung with bells",
    "a tortoise carried in a sling",
  ],
  wants: [
    "{They} wants the people near {place} to stop disturbing {their} meditation.",
    "{They} needs a rare herb {deadline} to finish a remedy.",
    "{They} wants to pass on a revelation before {they} forgets it.",
    "{They} wants news of {relation}, who {they} left behind long ago.",
    "{They} wants to buy salt, candles and nothing else, then go home.",
    "{They} has seen a vision and wants someone to tell {them} it isn't real.",
    "{They} wants to find an apprentice worthy of {their} knowledge.",
    "{They} needs the spring near {their} cave cleansed of something foul.",
    "{They} wants to return {item} to its owner, who must still be alive.",
    "{They} wants to warn the town about something, and nobody listens.",
    "{They} wants a book from the city library, and will not set foot in the city.",
    "{They} wants to find out why the birds have gone silent near {place}.",
  ],
  quirks: ["speaks in long silences", "talks to {their} pet crow as if it answers", "answers questions with riddles, then explains them badly", "measures time by the moon and nothing else"],
  fears: ["cities, and crowds of more than three", "what {they} saw in the vision", "being found by {their} old order", "the noise of the modern world"],
  secrets: [
    "{They} was once a famous scholar.",
    "{They} fled into isolation after a crime.",
    "{They} guards the entrance to something ancient below {their} hut.",
    "{They} is a former royal advisor who knows where the bodies are buried.",
  ],
};
