import type { BackgroundTables } from "./types";

export const merchant: BackgroundTables = {
  garment: [
    "a fur-trimmed coat",
    "a patched travelling cloak",
    "a dyed wool doublet",
    "a fine silk vest under a plain coat",
    "a merchant's robe with a guild sash",
    "a spice trader's bright turban and sash",
    "a caravan master's dusty duster coat",
    "a shopkeeper's apron over good clothes",
    "a velvet jacket with too many pockets",
    "a foreign robe from a land {they} trades with",
  ],
  accessory: [
    "ink-stained cuffs",
    "a ledger tucked under one arm",
    "rings on every finger",
    "a heavy purse chained to the belt",
    "a set of brass scales",
    "a sample case of fabrics",
    "an abacus hanging at the hip",
    "a pocket full of trade tokens",
    "a pair of reading spectacles",
    "a gold tooth that shows when {they} smiles",
  ],
  wants: [
    "{They} lent {their} cart to {relation} {timeAgo} and needs it back {deadline}.",
    "{They} owes {relation} money and is desperate to sell {item} {deadline}.",
    "{They} heard rumours of a cheaper supplier and wants to find out who it is.",
    "{They} wants an escort for a shipment passing through {place}.",
    "{They} wants to find out who is spreading lies about {their} prices.",
    "{They} has too much of one thing and wants to trade it {deadline}.",
    "{They} wants to open a second shop, in a rival's street.",
    "{They} needs a buyer for a crate of goods that arrived by mistake.",
    "{They} wants to recover a shipment lost near {place}.",
    "{They} wants a monopoly on salt, starting with this town.",
    "{They} wants to collect a debt from {relation} {deadline}, politely if possible.",
    "{They} needs someone to taste-test a new import, and won't say what it is.",
  ],
  quirks: ["puts a price on everything, including compliments", "bites every coin {they} receives", "haggles even when buying a gift", "remembers every customer's name and debts"],
  fears: ["bankruptcy", "bandits on the king's road", "a new tax", "a market crash"],
  secrets: [
    "{Their} scales are rigged.",
    "{They} sells stolen goods to a fence near {place}.",
    "{They} is smuggling something living in {their} crates.",
    "{They} is completely broke and running on credit and charm.",
  ],
};
