import type { BackgroundTables } from "./types";

export const noble: BackgroundTables = {
  garment: [
    "a tailored velvet doublet",
    "a brocade coat with silver thread",
    "a fine riding outfit",
    "a cloak lined with fur and embroidered with a crest",
    "silks a little too fine for the road",
    "a hunting jacket in the family colours",
    "a court outfit of the latest fashion",
    "a plain disguise that fools nobody",
    "an elegant mourning outfit",
    "an heirloom coat, slightly out of fashion",
  ],
  accessory: [
    "a family signet ring",
    "a jewelled dagger that has never been drawn",
    "perfectly kept hands",
    "a lace kerchief",
    "a servant trailing a few steps behind",
    "a perfumed pomander",
    "a falcon on a gloved wrist",
    "a sword with a gilded hilt",
    "a small dog in a jewelled collar",
    "a cameo brooch with a family portrait",
  ],
  wants: [
    "{They} needs to find a suitable marriage {deadline}, by family order.",
    "{They} wants to recover {item}, stolen from the family vault {timeAgo}.",
    "{They} wants revenge on a rival house, discreetly.",
    "{They} wants to prove {their} worth to a parent who prefers {their} sibling.",
    "{They} wants to see how commoners live, from a safe distance.",
    "{They} is hiding from a creditor and wants the debt quietly settled {deadline}.",
    "{They} wants to win back the family lands lost {timeAgo}.",
    "{They} needs a champion for a duel {deadline}.",
    "{They} wants to elope with {relation}, against everyone's wishes.",
    "{They} wants to host the ball of the season, and the budget is gone.",
    "{They} wants to find out who is leaking family secrets to the gossip sheets.",
    "{They} wants a seat on the council, and will do almost anything for it.",
  ],
  quirks: ["doesn't know how money works", "insists on full titles, always", "names all {their} horses after ancestors", "sniffs at anything {they} finds common"],
  fears: ["public scandal", "being disinherited", "poison at dinner", "the peasant uprising everyone whispers about"],
  secrets: [
    "The family fortune is gone, and {they} is pretending otherwise.",
    "{They} is a bastard and the heir knows it.",
    "{They} secretly funds the rebels.",
    "{They} was swapped at birth with a servant's child.",
  ],
};
