import type { BackgroundTables } from "./types";

export const sage: BackgroundTables = {
  garment: [
    "a scholar's robe with ink stains",
    "a long coat with bulging pockets of notes",
    "a faded academy gown",
    "a wool cardigan worn over everything",
    "simple robes with a too-large collar",
    "an astronomer's star-patterned mantle",
    "a herbalist's green smock",
    "a lecturer's black gown, chalk on the sleeves",
    "a tattered wizard's robe from a failed apprenticeship",
    "a scholar's travelling cloak lined with pockets",
  ],
  accessory: [
    "spectacles pushed up onto the forehead",
    "a satchel stuffed with scrolls",
    "a quill tucked behind one ear",
    "candle soot on the fingertips",
    "a magnifying lens on a string",
    "a skull used as a paperweight, carried around",
    "a star chart rolled under one arm",
    "an armful of books that keeps slipping",
    "a brass astrolabe at the belt",
    "a cat that sleeps on {their} notes",
  ],
  wants: [
    "{They} wants to find a missing page of an ancient text, last seen near {place}.",
    "{They} needs a rare book returned by {relation} {deadline}.",
    "{They} wants to prove a theory everyone laughs at.",
    "{They} wants a volunteer for a small, entirely safe experiment.",
    "{They} wants to translate an inscription {they} copied {timeAgo}.",
    "{They} wants to finish {their} treatise {deadline}, and has written one sentence.",
    "{They} wants to observe a comet from the top of {place} {deadline}.",
    "{They} wants a specimen of a creature that may not exist.",
    "{They} needs funding for an expedition, and has a very long proposal.",
    "{They} wants to debate someone, anyone, worthy of {their} intellect.",
    "{They} wants to know what {item} actually is.",
    "{They} wants to get back into the library {they} was banned from.",
  ],
  quirks: ["corrects everyone's pronunciation", "forgets to eat when reading", "lectures on any topic that comes up", "takes notes on conversations, openly"],
  fears: ["fire in the library", "being wrong in public", "the knowledge {they} has not yet found", "that {their} life's work is pointless"],
  secrets: [
    "{They} plagiarized {their} best-known work.",
    "{They} read something forbidden and still dreams about it.",
    "{They} knows the true name of a demon.",
    "{They} burned a book that would have changed history.",
  ],
};
