import type { BackgroundTables } from "./types";

export const sailor: BackgroundTables = {
  garment: [
    "a salt-stained coat",
    "a striped shirt and canvas trousers",
    "an oilskin jacket",
    "a knitted sweater that smells of the sea",
    "a bandana and loose breeches",
    "a navy officer's coat with a button missing",
    "a fisher's waders and a thick jumper",
    "a sailcloth vest, hand stitched",
    "a captain's hat that {they} definitely didn't earn",
    "a wide sash and bare feet",
  ],
  accessory: [
    "tattoos of anchors and stars",
    "a gold earring",
    "a knotted cord at the wrist",
    "a spyglass in the belt",
    "skin weathered by wind and sun",
    "a parrot with a foul vocabulary",
    "a whale-bone pipe",
    "a sailor's knife on a lanyard",
    "a shark tooth on a chain",
    "rope burns across both palms",
  ],
  wants: [
    "{They} needs a ship that sails {deadline}, any ship.",
    "{They} wants to find the captain who left {them} ashore {timeAgo}.",
    "{They} wants to win back {their} wages, which {they} lost at dice.",
    "{They} wants to know what happened to {their} old crew.",
    "{They} lent {their} sea chest to {relation} {timeAgo} and wants it back {deadline}.",
    "{They} wants to settle down on land, and hates it already.",
    "{They} wants a crew for a treasure hunt, with a map {they} won at cards.",
    "{They} needs to repair a boat {deadline}, and has no money for timber.",
    "{They} wants to find out what sank the fishing fleet {timeAgo}.",
    "{They} wants to get a letter to a sweetheart in a port far away.",
    "{They} wants to dodge the press gang until the navy ships leave.",
    "{They} wants to sell a sea-monster tooth that may be a cow's.",
  ],
  quirks: ["walks with a rolling gait even on land", "ties knots in anything within reach", "calls every floor a deck", "won't whistle indoors, it calls the wind"],
  fears: ["dying on dry land", "the thing {they} saw in the water", "a calm sea, which never lasts", "the sound of a ship's bell at night"],
  secrets: [
    "{They} was a pirate for three summers.",
    "{They} can't swim.",
    "{They} was the only survivor of a wreck, and knows why.",
    "{They} marked a treasure on a map and lost the map.",
  ],
};
