import type { BackgroundTables } from "./types";

export const scribe: BackgroundTables = {
  garment: [
    "a neat dark coat with ink-stained sleeves",
    "a plain tunic and a writing apron",
    "a clerk's gown with a high collar",
    "sleeve protectors over a wool shirt",
    "a sober grey outfit, impeccably pressed",
    "a court notary's black robe",
    "a copyist's smock, ink on every inch",
    "a modest coat with a pen case sewn into the lining",
    "a tax office uniform, faded",
    "a temple scribe's simple robe",
  ],
  accessory: [
    "a writing case on a strap",
    "a quill behind one ear",
    "squinting eyes",
    "a stack of sealed letters",
    "a little pot of ink tied at the belt",
    "a wax seal on a ribbon",
    "ink-blackened fingertips",
    "a ruler used as a pointer",
    "a ribbon of red tape around a bundle of papers",
    "half-moon spectacles on a chain",
  ],
  wants: [
    "{They} needs to deliver a contract to {relation} {deadline}.",
    "{They} wants to find out who altered a record {they} copied {timeAgo}.",
    "{They} wants a patron who pays on time.",
    "{They} misfiled an important document and needs it back {deadline}.",
    "{They} wants to write {their} own book instead of copying others'.",
    "{They} wants to read a letter {they} was told never to open.",
    "{They} needs a witness to sign a will {deadline}.",
    "{They} wants to find the author of an anonymous pamphlet.",
    "{They} wants to finish copying a huge ledger {deadline}, and needs help.",
    "{They} wants to recover pages lost in a fire at {place}.",
    "{They} wants to apply to the royal archive, and needs a reference.",
    "{They} wants to correct a record that wrongly lists {them} as dead.",
  ],
  quirks: ["writes down everything people say", "corrects spelling on public notices", "folds every piece of paper into neat squares", "sniffs new paper with real pleasure"],
  fears: ["losing {their} sight", "a smudged signature", "damp, and what it does to paper", "being replaced by a printing press"],
  secrets: [
    "{They} forges documents on the side.",
    "{They} read a letter {they} shouldn't have and knows something dangerous.",
    "{They} added {their} own name to a noble family's records.",
    "{They} keeps a copy of every secret letter {they} has ever written.",
  ],
};
