import type { BackgroundTables } from "./types";

export const soldier: BackgroundTables = {
  garment: [
    "a faded military coat",
    "a battered gambeson",
    "a chainmail shirt under a travelling cloak",
    "a regiment tunic with the insignia torn off",
    "worn leather armour",
    "a mercenary's mismatched plate",
    "an archer's green jerkin",
    "a cavalry coat with brass buttons",
    "a veteran's parade uniform, ill-fitting now",
    "a quartermaster's sensible coat",
  ],
  accessory: [
    "an old scar across the face",
    "a sword with a notched blade",
    "a medal kept polished",
    "a limp from an old wound",
    "the token of a fallen friend on a cord",
    "a shield with a painted-over crest",
    "a bow and a half-empty quiver",
    "a missing ear",
    "boots that have marched a thousand miles",
    "a soldier's pay ledger, still unpaid",
  ],
  wants: [
    "{They} wants to deliver a last letter from a fallen comrade to {relation}.",
    "{They} is owed back pay and wants it {deadline}.",
    "{They} wants to find the officer who abandoned {their} unit.",
    "{They} wants a quiet job where nobody shouts orders.",
    "{They} wants to train someone, so the old skills are good for something.",
    "{They} needs to report to {their} old commander {deadline}, and is dreading it.",
    "{They} wants to find the old regiment's lost banner, last seen at {place}.",
    "{They} wants to visit the graves of {their} unit before the season ends.",
    "{They} needs work as a sword for hire {deadline}.",
    "{They} wants to clear {their} name of a cowardice charge.",
    "{They} wants to open a tavern for veterans.",
    "{They} wants to know if the war is really over, and doesn't trust the answer.",
  ],
  quirks: ["wakes before dawn and can't help it", "salutes officers out of habit, even foreign ones", "sharpens {their} blade when thinking", "eats fast, as if the call to march might come any moment"],
  fears: ["loud noises at night", "another war", "the faces {they} sees in dreams", "becoming useless"],
  secrets: [
    "{They} deserted before the last battle.",
    "{They} took the credit for another soldier's bravery.",
    "{They} spared an enemy who later became a warlord.",
    "{They} fought for the other side once.",
  ],
};
