import type { BackgroundTables } from "./types";

export const wayfarer: BackgroundTables = {
  garment: [
    "a road-worn cloak",
    "layered clothes from many places",
    "a hooded coat with mismatched patches",
    "a sun-bleached shirt and travel boots",
    "a cloak with a dozen pinned badges from distant towns",
    "a poncho of foreign weave",
    "a pilgrim's grey robe",
    "a coat of many pockets, all full",
    "a beggar's rags with fine boots",
    "a hunter's jerkin won in a card game",
  ],
  accessory: [
    "a heavy pack",
    "a bedroll tied on top",
    "a staff of polished wood",
    "a pouch of trinkets from every town",
    "a dented tin cup on a cord",
    "a small mule called by a grand name",
    "a bundle of letters never answered",
    "a well-worn pair of dice",
    "a lantern rattling at the hip",
    "a map covered in {their} own notes",
  ],
  wants: [
    "{They} wants a warm bed and a hot meal {deadline}.",
    "{They} is looking for {relation}, who left a note saying to meet at {place}.",
    "{They} wants to reach a far city before winter closes the passes.",
    "{They} wants to trade a story for a ride on someone's cart.",
    "{They} wants to find somewhere {they} feels at home.",
    "{They} wants to know if the rumours about {place} are true.",
    "{They} needs to pay a toll {deadline} and has only {item} to offer.",
    "{They} wants to see the famous waterfall everyone talks about.",
    "{They} wants a travelling companion who doesn't talk too much.",
    "{They} wants to find the road {their} grandparent once walked.",
    "{They} wants to deliver a package for a stranger, and is starting to regret it.",
    "{They} wants to sleep for two days straight.",
  ],
  quirks: ["has a story about every town", "never stays two nights in the same bed", "sleeps better on the ground than in a bed", "collects local sayings and uses them wrong"],
  fears: ["staying in one place too long", "the road ending", "being forgotten by everyone {they} met", "a home {they} cannot leave"],
  secrets: [
    "{They} is running from something {they} won't name.",
    "{They} was born in this very town.",
    "{They} is carrying a message {they} has never read.",
    "{They} is an exiled heir, and the road is the only safe place.",
  ],
};
