import type { BackgroundTables } from "../../backgrounds/types";

export const acolyte: BackgroundTables = {
  garment: [
    "um manto de templo com capuz",
    "vestes cinzentas simples",
    "uma sobrepeliz branca sobre um hábito de lã",
    "uma capa de peregrino bordada com símbolos sagrados",
    "uma batina simples",
    "uma túnica de noviço, sem tingimento",
    "uma estola cerimonial sobre roupas de viagem",
    "um hábito de monge com cinto de corda",
    "uma túnica amarelo-sol de uma ordem da alvorada",
    "um manto negro de luto de um templo do deus da morte",
  ],
  accessory: [
    "um cordão de oração enrolado no pulso",
    "um símbolo sagrado de madeira preso a um cordão de couro",
    "um pequeno incensário que ainda cheira a incenso",
    "cera de vela respingada nas mangas",
    "um livro de hinos muito manuseado",
    "uma tonsura no alto da cabeça",
    "um frasco de água benta no cinto",
    "uma insígnia de peregrino de um santuário distante",
    "contas de oração gastas de tanto uso",
    "cinzas manchando a testa",
  ],
  wants: [
    "Precisa devolver ao templo uma relíquia emprestada {deadline}, e a perdeu de vista.",
    "Quer descobrir por que os sinos do templo tocaram sozinhos {timeAgo}.",
    "Está arrecadando esmolas para consertar um telhado e está bem longe do valor.",
    "Quer um sinal de seu deus e já começa a aceitar qualquer coisa como sinal.",
    "Precisa levar uma bênção a {relation} {deadline}, mas o caminho passa {place}.",
    "Quer se confessar a um sacerdote que não {o|a} conheça.",
    "Quer trazer {relation} de volta à fé, por bem ou por mal.",
    "Precisa de voluntários para limpar o santuário {place} {deadline}.",
    "Quer saber quem anda roubando velas da capela.",
    "Está em peregrinação e, para sua vergonha, perdeu o caminho.",
    "Quer copiar um texto sagrado que o sumo sacerdote mantém trancado.",
    "Precisa de alguém para velar um desconhecido moribundo esta noite.",
  ],
  quirks: [
    "abençoa comida, portas e, às vezes, pessoas, sem pedir licença",
    "cita as escrituras nos piores momentos possíveis",
    "reza em voz alta antes de cada decisão pequena",
    "jejua nos feriados santos mais estranhos, e faz questão de comentar",
  ],
  fears: ["que seu deus tenha parado de ouvir {timeAgo}", "perder a fé diante dos outros", "hereges e o quanto sabem ser persuasivos", "morrer sem absolvição"],
  secrets: [
    "Roubou a caixa de ofertas uma vez para alimentar a família.",
    "Não tem certeza de que seu deus existe, e prega mesmo assim.",
    "Foi mandad{o|a} ao templo como castigo, não por escolha.",
    "Anda tendo visões, e elas não vêm de seu deus.",
  ],
};
