import type { BackgroundTables } from "../../backgrounds/types";

export const artisan: BackgroundTables = {
  garment: [
    "um avental de couro sobre uma camisa de mangas arregaçadas",
    "um guarda-pó resistente coberto de serragem",
    "uma tabarda de guilda com um brasão desbotado",
    "um casaco de lona com marcas de queimadura nos punhos",
    "uma túnica simples manchada de tintura",
    "uma camisa de oleiro manchada de argila",
    "um colete de lã colorido de tecelão",
    "um gibão de couro chamuscado de vidreiro",
    "calças resistentes de sapateiro com joelheiras remendadas",
    "um gibão fino, mas simples, de joalheiro",
  ],
  accessory: [
    "um cinto de ferramentas pequenas",
    "mãos calejadas e manchadas de tinta",
    "um lápis atrás da orelha",
    "uma corda de medir enrolada no quadril",
    "uma lupa de joalheiro presa a uma corrente",
    "uma ficha de guilda presa no colarinho",
    "um polegar enfaixado",
    "aparas de madeira presas no cabelo",
    "uma amostra do próprio trabalho, usada com orgulho",
    "luvas grossas de couro enfiadas no cinto",
  ],
  wants: [
    "Prometeu uma obra-prima a {relation} {deadline} e mal começou.",
    "Quer encontrar um material raro que só aparece {place}.",
    "Precisa renovar o selo da guilda {deadline}, e o mestre da guilda não o suporta.",
    "Quer provar que um rival copiou seu projeto.",
    "Emprestou suas melhores ferramentas a {relation} {timeAgo} e quer tudo de volta {deadline}.",
    "Quer que alguém, qualquer um, finalmente pague pela última encomenda.",
    "Precisa de um aprendiz que não quebre tudo {deadline}.",
    "Quer participar da feira de ofícios e, desta vez, ganhar.",
    "Quer descobrir quem anda comprando todas as suas peças e por quê.",
    "Precisa de uma nova oficina depois que o senhorio dobrou o aluguel.",
    "Quer que um nobre use uma de suas obras em público.",
    "Quer recriar uma técnica perdida sobre a qual leu {timeAgo}.",
  ],
  quirks: [
    "avalia cada cadeira em que se senta",
    "não consegue parar de consertar coisas que não estão quebradas",
    "passa os dedos por toda superfície para sentir a textura",
    "assina suas obras num lugar onde ninguém jamais olharia",
  ],
  fears: ["perder o movimento das mãos", "morrer antes de fazer uma peça realmente grandiosa", "a nova oficina da rua de baixo", "um cliente que sabe exatamente o que quer"],
  secrets: [
    "A obra mais famosa {dele|dela} foi feita por um aprendiz.",
    "Falsificou a marca da guilda para conseguir a primeira encomenda.",
    "Esconde um defeito em cada peça, de propósito.",
    "Certa vez fez uma chave para um arrombador, sabendo muito bem disso.",
  ],
};
