import type { BackgroundTables } from "../../backgrounds/types";

export const charlatan: BackgroundTables = {
  garment: [
    "um gibão um tanto chamativo demais",
    "um casaco de veludo com botões de falso ouro",
    "uma capa de nobre emprestada",
    "uma roupa de arlequim remendada de mascate",
    "um traje de mercador respeitável que cai meio estranho",
    "um xale de miçangas de cartomante",
    "uma túnica de padre que não tem direito de usar",
    "uma capa vistosa forrada de seda barata",
    "um casaco escuro de médico, sem o estudo",
    "um traje sóbrio de escrivão, para parecer confiável",
  ],
  accessory: [
    "um anel que deixa o dedo esverdeado",
    "um baralho marcado",
    "um frasco de 'tônico milagroso'",
    "uma carta de apresentação falsificada",
    "três nomes diferentes costurados dentro do colarinho",
    "um sorriso falso deslumbrante",
    "um monóculo de vidro comum",
    "uma bola de cristal embrulhada em seda",
    "um maço de papéis de aparência muito oficial",
    "uma peruca ligeiramente torta",
  ],
  wants: [
    "Precisa sair da cidade {deadline}, porque {relation} começou a fazer perguntas.",
    "Quer vender um último lote de tônico milagroso antes que alguém o teste.",
    "Quer recuperar {item}, que perdeu num jogo de cartas {timeAgo}.",
    "Procura um sócio para um golpe grande, com cara de negócio honesto.",
    "Quer uma nova identidade {deadline} e já tem alguns candidatos em mente.",
    "Quer encontrar o vigarista que {o|a} enganou, por orgulho profissional.",
    "Quer arranjar um casamento rico {deadline} e anda testando candidatos.",
    "Precisa de alguém para fingir ser um parente há muito desaparecido por uma noite.",
    "Quer vender a escritura de uma propriedade {place}, que não lhe pertence.",
    "Precisa de uma relíquia falsa convincente {deadline}.",
    "Quer se aposentar, assim que este último golpe der certo.",
    "Quer voltar às boas graças de {relation}, a quem enganou.",
  ],
  quirks: ["responde a toda pergunta com outra pergunta", "troca de sotaque no meio da frase", "elogia todo mundo, com generosidade e sem parar", "mantém as mãos à vista de todos, de um jeito um pouco proposital demais"],
  fears: ["encontrar alguém que {o|a} tenha enganado", "trabalho honesto", "uma cidade onde todos se conhecem", "ser acreditad{o|a} justamente quando enfim diz a verdade"],
  secrets: [
    "Acredita de verdade que o tônico funciona.",
    "É procurad{o|a} sob quatro nomes diferentes.",
    "Dá quase tudo o que rouba a um orfanato.",
    "A adivinhação 'de mentira' {dele|dela} anda assustadoramente certeira.",
  ],
};
