import type { BackgroundTables } from "../../backgrounds/types";

export const criminal: BackgroundTables = {
  garment: [
    "um casaco escuro com capuz",
    "calças remendadas e botas de sola macia",
    "o colete roubado de um cavalheiro",
    "um cachecol usado alto, cobrindo o rosto",
    "uma camisa simples cheia de bolsos escondidos",
    "a jaqueta áspera de um estivador",
    "um gibão de couro preto, untado para não fazer barulho",
    "uma libré de criado, tomada emprestada sem pedir",
    "uma capa cinzenta que some em qualquer multidão",
    "roupas finas sem as etiquetas do alfaiate",
  ],
  accessory: [
    "uma faca pequena escondida na manga",
    "um molho de gazuas",
    "uma cicatriz atravessando os nós dos dedos",
    "uma tatuagem de gangue no pulso",
    "olhos que não param de vigiar as saídas",
    "um nariz quebrado que colou torto",
    "um rolo de corda fina sob o casaco",
    "uma bolsa que claramente pertence a outra pessoa",
    "a ponta de um dedo faltando",
    "uma marca de ferro no ombro, meio escondida",
  ],
  wants: [
    "Deve a {relation} por um serviço que deu errado e precisa do dinheiro {deadline}.",
    "Quer recuperar {item}, que escondeu {place} {timeAgo}.",
    "Quer sair da gangue, com vida.",
    "Precisa de um álibi para a noite passada, {deadline}.",
    "Quer descobrir quem {o|a} delatou {timeAgo}.",
    "Está planejando um último serviço e precisa de mais um par de mãos.",
    "Precisa de um lugar seguro para se esconder {deadline}.",
    "Quer tirar {relation} da cadeia.",
    "Quer passar adiante {item} sem que a guilda leve sua parte.",
    "Precisa de um salvo-conduto falso {deadline}.",
    "Quer vingança contra o receptador que {o|a} enganou.",
    "Quer largar a vida do crime e não faz ideia de como.",
  ],
  quirks: ["sempre paga com o troco exato", "sabe de cor o turno de cada guarda", "conta as portas de todo cômodo em que entra", "nunca dá o mesmo nome duas vezes"],
  fears: ["a prisão", "que seu antigo bando {o|a} encontre", "a forca {place}", "o cobrador da guilda"],
  secrets: [
    "Trabalha para a guarda da cidade como informante.",
    "Nunca matou ninguém de fato, apesar dos boatos que espalhou.",
    "Foi quem roubou {relation} e agora finge ajudar a encontrar o ladrão.",
    "É fil{ho|ha} de um magistrado.",
  ],
};
