import type { BackgroundTables } from "../../backgrounds/types";

export const entertainer: BackgroundTables = {
  garment: [
    "um traje vistoso de retalhos",
    "um chapéu de plumas e uma capa colorida",
    "uma camisa de seda de artista, com os laços frouxos",
    "um casaco de bobo da corte sem os guizos",
    "um vestido de palco puído na barra",
    "um couro justo de acrobata",
    "um longo casaco de contador de histórias bordado de estrelas",
    "saias esvoaçantes de dançarina sobre botas resistentes",
    "um gibão de menestrel em duas cores berrantes",
    "uma capa negra de vilão de teatro, usada até fora do palco",
  ],
  accessory: [
    "um alaúde com uma corda faltando",
    "uma maquiagem de teatro que não saiu por completo",
    "uma bolsa de malabarismo na cintura",
    "um pandeiro surrado",
    "um punhado de panfletos do espetáculo desta noite",
    "um apito de lata enfiado no cinto",
    "uma máscara pendurada num cordão",
    "um brilho que se recusa a sair",
    "uma flor presa na lapela, meio murcha",
    "um par de dados da sorte que nunca são usados",
  ],
  wants: [
    "Precisa de uma plateia {deadline}, ou a trupe passa fome.",
    "Quer se apresentar para um nobre e aceita mentir sobre seus talentos para conseguir.",
    "Quer encontrar o rival que roubou sua melhor canção.",
    "Emprestou o baú de figurinos para {relation} {timeAgo} e precisa dele de volta {deadline}.",
    "Quer que alguém escreva um número novo, porque o antigo anda sendo vaiado.",
    "Procura um novo parceiro, depois que o último fugiu com a féria.",
    "Quer uma história verdadeira para virar balada, quanto mais perigosa, melhor.",
    "Precisa de um palco {deadline}, já que o último pegou fogo.",
    "Quer descobrir quem vive atirando repolhos nos seus espetáculos.",
    "Quer vencer o concurso de bardos {place}.",
    "Quer proibir uma canção sobre {relation} antes que a notícia se espalhe.",
    "Quer se aposentar dos palcos e ainda não contou à trupe.",
  ],
  quirks: [
    "narra a própria vida em rimas",
    "faz uma reverência ao terminar qualquer frase de que se orgulha",
    "não consegue passar por uma plateia sem se apresentar",
    "cantarola a própria música de entrada",
  ],
  fears: ["uma plateia vazia", "esquecer a letra no palco", "um crítico que já zombou {dele|dela}", "ser comum"],
  secrets: [
    "Na verdade, não sabe ler partitura.",
    "É {um nobre deserdado|uma nobre deserdada} escondid{o|a} à vista de todos.",
    "Carrega mensagens para uma rede de espiões escondidas nas suas canções.",
    "Sua canção mais famosa foi escrita por alguém que morreu pobre.",
  ],
};
