import type { BackgroundTables } from "../../backgrounds/types";

export const farmer: BackgroundTables = {
  garment: [
    "um chapéu de palha e uma camisa manchada de suor",
    "botas robustas cobertas de lama",
    "um guarda-pó de pano grosso com os joelhos remendados",
    "um casaco de pano encerado",
    "um colete de lã sobre as mangas arregaçadas",
    "um macacão preso com barbante",
    "uma pesada capa de pastor com capuz",
    "uma camisa de linho desbotada pelo sol",
    "uma jaqueta de pele de carneiro",
    "o melhor casaco dos dias de feira, um pouco apertado demais",
  ],
  accessory: [
    "um pescoço queimado de sol",
    "um forcado apoiado no ombro",
    "sementes chacoalhando no bolso",
    "uma bolsinha de fumo de cachimbo",
    "um lenço amarrado no pescoço",
    "palha presa no cabelo",
    "um cesto de ovos, carregado com todo o cuidado",
    "um cajado de pastor",
    "terra sob cada unha",
    "um cão pastor que o segue por toda parte",
  ],
  wants: [
    "Perdeu um bode premiado {place} e quer tê-lo de volta {deadline}.",
    "Precisa de ajuda para recolher a colheita {deadline}.",
    "Quer saber o que anda pisoteando seus campos à noite.",
    "Emprestou o cavalo de arado para {relation} {timeAgo} e precisa dele de volta {deadline}.",
    "Quer, pela primeira vez, um preço justo pela colheita.",
    "Quer casar um filho e entrevista qualquer um que passe.",
    "Quer vencer o concurso de abóbora gigante da feira.",
    "Precisa de chuva {deadline} e pagará a quem conseguir trazê-la.",
    "Quer saber por que as vacas pararam de dar leite {timeAgo}.",
    "Quer que {relation} pare de deixar os porcos entrarem no seu pomar.",
    "Precisa de uma cura para a doença que se espalha pelo rebanho.",
    "Quer conhecer a capital pelo menos uma vez antes de morrer.",
  ],
  quirks: [
    "prevê o tempo e costuma errar",
    "conversa com as plantações, chamando cada uma pelo nome",
    "acorda antes do galo e se ressente disso",
    "julga as pessoas pelo estado das botas",
  ],
  fears: ["uma colheita perdida", "a coisa que vive no poço velho", "gafanhotos", "o capataz do senhorio"],
  secrets: [
    "Encontrou uma pedra estranha no campo e não contou a ninguém.",
    "Mudou os marcos de divisa de lugar numa noite.",
    "Alimenta toda noite uma criatura da mata para que ela deixe o rebanho em paz.",
    "É {o verdadeiro herdeiro|a verdadeira herdeira} das terras que arrenda.",
  ],
};
