import type { BackgroundTables } from "../../backgrounds/types";

export const guard: BackgroundTables = {
  garment: [
    "um peitoral amassado sobre um gibão acolchoado",
    "um tabardo da guarda da cidade",
    "uma cota de malha sob uma capa pesada",
    "uma couraça de couro com fivelas polidas",
    "um uniforme um pouco apertado demais",
    "o longo casaco azul de um guarda de portão",
    "a libré da guarda particular de uma casa nobre",
    "uma camisa de folga que ainda parece um uniforme",
    "uma armadura desencontrada de guarda de caravana",
    "um tabardo cerimonial do palácio, bastante desbotado",
  ],
  accessory: [
    "um porrete pendurado no cinto",
    "um apito num cordão",
    "um molho de chaves pesadas",
    "um elmo cheio de cicatrizes sob o braço",
    "uma lanterna para a ronda noturna",
    "uma alabarda que já viu dias melhores",
    "um caderninho de rostos suspeitos",
    "um distintivo polido até brilhar",
    "um par de algemas de ferro",
    "um cantil que com certeza não tem água",
  ],
  wants: [
    "Precisa encontrar um prisioneiro fugido {deadline}, antes que o capitão perceba.",
    "Quer ser transferid{o|a} do portão que fica {place}.",
    "Quer provas de que {relation} anda contrabandeando mercadorias.",
    "Perdeu as chaves da prisão {timeAgo} e precisa recuperá-las {deadline}.",
    "Quer uma promoção e fará questão de prender alguém importante para merecê-la.",
    "Quer um turno tranquilo, só um.",
    "Quer saber quem anda deixando marcas estranhas no portão à noite.",
    "Precisa de alguém para cobrir seu turno {deadline}.",
    "Quer encontrar o ladrão que roubou sua espada durante o serviço.",
    "Quer pegar o batedor de carteiras que não larga a sua rua.",
    "Quer provar a inocência de {relation} num crime que presenciou.",
    "Quer o soldo atrasado que a cidade lhe deve desde {timeAgo}.",
  ],
  quirks: [
    "desafia todo mundo com um \"alto lá, quem vem lá?\" por hábito",
    "mantém a contagem de cada prisão que fez",
    "fica em posição de sentido sem perceber",
    "confere todas as fechaduras por onde passa",
  ],
  fears: [
    "levar a culpa por algo que não fez",
    "o motim que certamente está por vir",
    "os becos escuros que ficam {place}",
    "o temperamento do capitão",
  ],
  secrets: [
    "Aceita suborno, pequeno, com regularidade.",
    "Deixou um prisioneiro fugir {timeAgo}, por pena.",
    "Dormiu durante a noite em que o cofre foi roubado.",
    "É parente do ladrão mais procurado da cidade.",
  ],
};
