import type { BackgroundTables } from "../../backgrounds/types";

export const guide: BackgroundTables = {
  garment: [
    "uma capa de patrulheiro castigada pelo tempo",
    "um capuz forrado de pele",
    "botas amaciadas por tanto caminhar",
    "um casaco de couro com mangas franjadas",
    "camadas de verdes e marrons discretos",
    "uma capa encerada que espanta a chuva",
    "uma jaqueta acolchoada de alpinista",
    "um manto de deserto contra o sol e a areia",
    "uma túnica com folhas costuradas para camuflagem",
    "uma roupa de camurça remendada de caçador",
  ],
  accessory: [
    "uma corda enrolada sobre o ombro",
    "um mapa desenhado à mão enfiado no cinto",
    "um cajado de caminhada cheio de entalhes",
    "uma trompa de caça",
    "carrapichos grudados em toda a barra da roupa",
    "uma bússola num cordão de couro",
    "uma pena de falcão no chapéu",
    "uma funda e uma bolsa de pedras",
    "um odre que parece nunca estar cheio",
    "um colar de dentes de animais",
  ],
  wants: [
    "Precisa de viajantes para guiar {deadline} e não é exigente.",
    "Quer encontrar a trilha perdida que passa {place}.",
    "Perdeu um cliente na floresta {timeAgo} e quer descobrir o que aconteceu.",
    "Quer mapear uma região de onde ninguém voltou.",
    "Emprestou seu melhor mapa a {relation} {timeAgo} e quer de volta {deadline}.",
    "Quer se aposentar num lugar que tenha telhado.",
    "Quer rastrear a fera que anda matando os cervos {place}.",
    "Precisa atravessar o desfiladeiro {deadline}, antes que a neve o feche.",
    "Quer uma escolta pelo território dos bandoleiros, por ironia do destino.",
    "Quer provar que a estrada velha ainda é segura, para ganhar uma aposta.",
    "Quer descobrir a origem das luzes estranhas sobre as colinas.",
    "Quer ensinar as trilhas a alguém antes que os joelhos cedam.",
  ],
  quirks: [
    "fareja o ar antes de cada decisão",
    "se recusa a dormir sob um teto",
    "lê pegadas de animais em voz alta como se fossem fofoca",
    "dá direções usando árvores que ninguém mais consegue distinguir",
  ],
  fears: [
    "se perder, o que jamais admitiria",
    "o que quer que ande pela floresta à noite",
    "lobos que andam sobre duas pernas",
    "um cliente que não dá ouvidos",
  ],
  secrets: [
    "Na verdade, nunca esteve em metade dos lugares que diz conhecer.",
    "Uma vez levou um grupo para uma emboscada em troca de dinheiro.",
    "Conhece uma entrada secreta para a cidade que mais ninguém conhece.",
    "Fez um pacto com os espíritos da floresta.",
  ],
};
