import type { BackgroundTables } from "../../backgrounds/types";

export const hermit: BackgroundTables = {
  garment: [
    "um manto remendado de lã crua",
    "peles costuradas à mão",
    "uma túnica áspera de aniagem",
    "uma capa esfarrapada de muitas cores, todas desbotadas",
    "um manto com ervas presas nas costuras",
    "uma capa de juncos trançados",
    "um hábito de monge com décadas de uso",
    "camadas de cobertores roídos por traças",
    "um xale verde-musgo que talvez seja musgo de verdade",
    "um belo casaco de outra vida, agora em frangalhos",
  ],
  accessory: [
    "terra sob cada unha",
    "um cajado retorcido",
    "um feixe de ervas secas",
    "um colar de ossinhos",
    "um corvo de estimação que raramente se afasta",
    "pés descalços e calejados",
    "um cachimbo de barro que nunca é aceso",
    "uma sacola de cogumelos estranhos",
    "um bordão enfeitado de guizos",
    "uma tartaruga carregada numa tipoia",
  ],
  wants: [
    "Quer que as pessoas que vivem {place} parem de atrapalhar sua meditação.",
    "Precisa de uma erva rara {deadline} para terminar um remédio.",
    "Quer transmitir uma revelação antes de esquecê-la.",
    "Quer notícias de {relation}, que deixou para trás há muito tempo.",
    "Quer comprar sal, velas e mais nada, e então voltar para casa.",
    "Teve uma visão e quer que alguém lhe diga que não é real.",
    "Quer encontrar um aprendiz digno do seu conhecimento.",
    "Precisa que a nascente perto da sua caverna seja limpa de algo imundo.",
    "Quer devolver {item} ao dono, que ainda deve estar vivo.",
    "Quer avisar a cidade sobre uma ameaça, mas ninguém dá ouvidos.",
    "Quer um livro da biblioteca da cidade e não pisará lá de jeito nenhum.",
    "Quer descobrir por que os pássaros silenciaram {place}.",
  ],
  quirks: [
    "fala em longos silêncios",
    "conversa com o corvo de estimação como se ele respondesse",
    "responde a perguntas com charadas e depois as explica mal",
    "mede o tempo pela lua e por mais nada",
  ],
  fears: [
    "as cidades e as multidões com mais de três pessoas",
    "o que viu na visão",
    "ser encontrad{o|a} pela antiga ordem",
    "o barulho do mundo moderno",
  ],
  secrets: [
    "Já foi {um estudioso famoso|uma estudiosa famosa}.",
    "Fugiu para o isolamento depois de cometer um crime.",
    "Guarda a entrada de algo antigo sob a sua cabana.",
    "É {um ex-conselheiro real|uma ex-conselheira real} e sabe onde os corpos estão enterrados.",
  ],
};
