import type { BackgroundTables } from "../../backgrounds/types";

export const merchant: BackgroundTables = {
  garment: [
    "um casaco com gola de pele",
    "uma capa de viagem remendada",
    "um gibão de lã tingida",
    "um fino colete de seda sob um casaco simples",
    "uma túnica de mercador com a faixa da guilda",
    "um turbante colorido e uma faixa de mercador de especiarias",
    "um casaco empoeirado de chefe de caravana",
    "um avental de lojista sobre roupas finas",
    "uma jaqueta de veludo com bolsos demais",
    "uma túnica estrangeira, de uma terra com a qual negocia",
  ],
  accessory: [
    "punhos manchados de tinta",
    "um livro-caixa enfiado sob o braço",
    "anéis em todos os dedos",
    "uma bolsa pesada presa ao cinto por uma corrente",
    "uma balança de latão",
    "uma maleta de amostras de tecidos",
    "um ábaco pendurado na cintura",
    "um bolso cheio de fichas de comércio",
    "um par de óculos de leitura",
    "um dente de ouro que aparece quando sorri",
  ],
  wants: [
    "Emprestou sua carroça a {relation} {timeAgo} e precisa dela de volta {deadline}.",
    "Deve dinheiro a {relation} e está desesperad{o|a} para vender {item} {deadline}.",
    "Ouviu boatos de um fornecedor mais barato e quer descobrir quem é.",
    "Quer uma escolta para uma carga que vai passar {place}.",
    "Quer descobrir quem espalha mentiras sobre os seus preços.",
    "Tem coisa demais de um só produto e quer trocá-la {deadline}.",
    "Quer abrir uma segunda loja, na rua de um concorrente.",
    "Precisa de um comprador para uma caixa de mercadorias que chegou por engano.",
    "Quer recuperar uma carga perdida {place}.",
    "Quer o monopólio do sal, começando por esta cidade.",
    "Quer cobrar uma dívida de {relation} {deadline}, com educação, se possível.",
    "Precisa de alguém para provar uma nova importação, e não diz o que é.",
  ],
  quirks: [
    "dá preço a tudo, até a elogios",
    "morde cada moeda que recebe",
    "pechincha até quando compra um presente",
    "lembra o nome e as dívidas de cada cliente",
  ],
  fears: ["a falência", "bandoleiros na estrada do rei", "um novo imposto", "a quebra do mercado"],
  secrets: [
    "Sua balança é adulterada.",
    "Vende mercadoria roubada a um receptador que atua {place}.",
    "Contrabandeia algo vivo dentro das suas caixas.",
    "Está completamente falid{o|a} e vive de crédito e lábia.",
  ],
};
