import type { BackgroundTables } from "../../backgrounds/types";

export const noble: BackgroundTables = {
  garment: [
    "um gibão de veludo sob medida",
    "um casaco de brocado com fios de prata",
    "um fino traje de montaria",
    "uma capa forrada de pele e bordada com um brasão",
    "sedas um pouco finas demais para a estrada",
    "uma jaqueta de caça nas cores da família",
    "um traje de corte na última moda",
    "um disfarce simples que não engana ninguém",
    "um elegante traje de luto",
    "um casaco de herança, um pouco fora de moda",
  ],
  accessory: [
    "um anel de sinete da família",
    "uma adaga cravejada de joias que nunca foi desembainhada",
    "mãos perfeitamente cuidadas",
    "um lenço de renda",
    "um criado que segue alguns passos atrás",
    "um sachê perfumado",
    "um falcão pousado num pulso enluvado",
    "uma espada com punho dourado",
    "um cãozinho com coleira de joias",
    "um broche de camafeu com o retrato da família",
  ],
  wants: [
    "Precisa arranjar um casamento adequado {deadline}, por ordem da família.",
    "Quer recuperar {item}, roubado do cofre da família {timeAgo}.",
    "Quer se vingar de uma casa rival, com discrição.",
    "Quer provar seu valor a um dos pais, que prefere um dos irmãos.",
    "Quer ver como vive o povo comum, a uma distância segura.",
    "Está se escondendo de um credor e quer a dívida quitada em silêncio {deadline}.",
    "Quer reaver as terras da família, perdidas {timeAgo}.",
    "Precisa de um campeão para um duelo {deadline}.",
    "Quer fugir com {relation}, contra a vontade de todos.",
    "Quer dar o baile da temporada, mas o orçamento acabou.",
    "Quer descobrir quem vaza os segredos da família para os pasquins de fofoca.",
    "Quer uma cadeira no conselho e fará quase qualquer coisa por ela.",
  ],
  quirks: [
    "não faz ideia de como o dinheiro funciona",
    "insiste em usar os títulos completos, sempre",
    "dá aos cavalos o nome de antepassados",
    "torce o nariz para tudo que acha vulgar",
  ],
  fears: ["um escândalo público", "ser deserdad{o|a}", "veneno no jantar", "a revolta camponesa de que todos cochicham"],
  secrets: [
    "A fortuna da família acabou, e finge que não.",
    "É {um bastardo|uma bastarda}, e o herdeiro legítimo sabe disso.",
    "Financia os rebeldes em segredo.",
    "Foi trocad{o|a} no berço com o filho de um criado.",
  ],
};
