import type { BackgroundTables } from "../../backgrounds/types";

export const sage: BackgroundTables = {
  garment: [
    "uma toga de erudito manchada de tinta",
    "um longo casaco com bolsos estufados de anotações",
    "uma beca desbotada da academia",
    "um casaco de lã usado por cima de tudo",
    "vestes simples com uma gola grande demais",
    "um manto de astrônomo estampado de estrelas",
    "um guarda-pó verde de herbalista",
    "uma beca negra de professor, com giz nas mangas",
    "uma túnica de mago esfarrapada, de um aprendizado fracassado",
    "uma capa de viagem de estudioso forrada de bolsos",
  ],
  accessory: [
    "óculos empurrados para a testa",
    "uma sacola recheada de pergaminhos",
    "uma pena de escrever atrás da orelha",
    "fuligem de vela nas pontas dos dedos",
    "uma lente de aumento pendurada num barbante",
    "um crânio usado como peso de papel, levado para todo lado",
    "um mapa estelar enrolado sob o braço",
    "uma braçada de livros que não para de escorregar",
    "um astrolábio de latão no cinto",
    "um gato que dorme sobre suas anotações",
  ],
  wants: [
    "Quer encontrar a página perdida de um texto antigo, vista pela última vez {place}.",
    "Precisa que {relation} devolva um livro raro {deadline}.",
    "Quer provar uma teoria da qual todos riem.",
    "Quer um voluntário para um pequeno experimento, totalmente seguro.",
    "Quer traduzir uma inscrição que copiou {timeAgo}.",
    "Quer terminar seu tratado {deadline}, e só escreveu uma frase.",
    "Quer observar um cometa do alto do lugar {place} {deadline}.",
    "Quer um espécime de uma criatura que talvez nem exista.",
    "Precisa de financiamento para uma expedição e tem uma proposta longuíssima.",
    "Quer debater com alguém, qualquer um, que seja digno do seu intelecto.",
    "Quer saber o que {item} realmente é.",
    "Quer voltar à biblioteca da qual foi banid{o|a}.",
  ],
  quirks: [
    "corrige a pronúncia de todo mundo",
    "esquece de comer quando está lendo",
    "dá palestra sobre qualquer assunto que surja",
    "faz anotações das conversas, abertamente",
  ],
  fears: [
    "fogo na biblioteca",
    "errar em público",
    "o conhecimento que ainda não encontrou",
    "que a obra da sua vida seja inútil",
  ],
  secrets: [
    "Plagiou sua obra mais conhecida.",
    "Leu algo proibido e ainda sonha com isso.",
    "Conhece o verdadeiro nome de um demônio.",
    "Queimou um livro que teria mudado a história.",
  ],
};
