import type { BackgroundTables } from "../../backgrounds/types";

export const sailor: BackgroundTables = {
  garment: [
    "um casaco manchado de sal",
    "uma camisa listrada e calças de lona",
    "uma jaqueta de pano encerado",
    "um suéter de tricô com cheiro de mar",
    "uma bandana e calções largos",
    "um casaco de oficial da marinha com um botão faltando",
    "botas de pescador e um grosso suéter",
    "um colete de lona de vela, costurado à mão",
    "um chapéu de capitão que com certeza não foi conquistado",
    "uma larga faixa na cintura e os pés descalços",
  ],
  accessory: [
    "tatuagens de âncoras e estrelas",
    "um brinco de ouro",
    "um cordão com nós no pulso",
    "uma luneta enfiada no cinto",
    "uma pele curtida pelo vento e pelo sol",
    "um papagaio de vocabulário chulo",
    "um cachimbo de osso de baleia",
    "uma faca de marujo presa a um cordão",
    "um dente de tubarão numa corrente",
    "marcas de corda nas duas palmas",
  ],
  wants: [
    "Precisa de um navio que zarpe {deadline}, qualquer navio.",
    "Quer encontrar o capitão que {o|a} deixou em terra {timeAgo}.",
    "Quer recuperar o soldo que perdeu nos dados.",
    "Quer saber o que aconteceu com a sua antiga tripulação.",
    "Emprestou seu baú de marinheiro a {relation} {timeAgo} e quer de volta {deadline}.",
    "Quer sossegar em terra firme, e já detesta a ideia.",
    "Quer uma tripulação para uma caça ao tesouro, com um mapa que ganhou no carteado.",
    "Precisa consertar um barco {deadline} e não tem dinheiro para a madeira.",
    "Quer descobrir o que afundou a frota pesqueira {timeAgo}.",
    "Quer fazer uma carta chegar a um amor num porto distante.",
    "Quer fugir do recrutamento forçado até que os navios da marinha partam.",
    "Quer vender um dente de monstro marinho que talvez seja de vaca.",
  ],
  quirks: [
    "anda balançando como em alto-mar, até em terra",
    "dá nós em tudo que estiver ao alcance",
    "chama qualquer chão de convés",
    "não assobia em ambientes fechados, porque isso chama o vento",
  ],
  fears: [
    "morrer em terra firme",
    "a coisa que viu na água",
    "o mar calmo demais, que nunca dura",
    "o som do sino de um navio à noite",
  ],
  secrets: [
    "Foi pirata durante três verões.",
    "Não sabe nadar.",
    "É {o único sobrevivente|a única sobrevivente} de um naufrágio e sabe por quê.",
    "Marcou um tesouro num mapa e perdeu o mapa.",
  ],
};
