import type { BackgroundTables } from "../../backgrounds/types";

export const scribe: BackgroundTables = {
  garment: [
    "um casaco escuro e alinhado, com as mangas manchadas de tinta",
    "uma túnica simples e um avental de escrita",
    "uma beca de escrivão com gola alta",
    "protetores de manga sobre uma camisa de lã",
    "um traje cinza e sóbrio, impecavelmente passado",
    "a toga negra de um tabelião da corte",
    "um guarda-pó de copista, com tinta em cada palmo",
    "um casaco modesto com um estojo de penas costurado no forro",
    "um uniforme desbotado da coletoria de impostos",
    "o hábito simples de um escriba de templo",
  ],
  accessory: [
    "um estojo de escrita a tiracolo",
    "uma pena atrás da orelha",
    "olhos apertados de tanto forçar a vista",
    "uma pilha de cartas lacradas",
    "um potinho de tinta amarrado ao cinto",
    "um selo de cera preso a uma fita",
    "pontas dos dedos pretas de tinta",
    "uma régua usada como ponteiro",
    "uma fita vermelha da burocracia amarrando um maço de papéis",
    "óculos de meia-lua pendurados numa corrente",
  ],
  wants: [
    "Precisa entregar um contrato a {relation} {deadline}.",
    "Quer descobrir quem alterou um registro que copiou {timeAgo}.",
    "Quer um patrono que pague em dia.",
    "Arquivou errado um documento importante e precisa dele de volta {deadline}.",
    "Quer escrever o próprio livro, em vez de copiar os dos outros.",
    "Quer ler uma carta que mandaram nunca abrir.",
    "Precisa de uma testemunha para assinar um testamento {deadline}.",
    "Quer descobrir o autor de um panfleto anônimo.",
    "Quer terminar de copiar um livro-caixa enorme {deadline} e precisa de ajuda.",
    "Quer recuperar páginas perdidas num incêndio {place}.",
    "Quer se candidatar ao arquivo real e precisa de uma carta de recomendação.",
    "Quer corrigir um registro que {o|a} dá erroneamente como mort{o|a}.",
  ],
  quirks: [
    "anota tudo que as pessoas dizem",
    "corrige a ortografia dos avisos públicos",
    "dobra cada folha de papel em quadradinhos perfeitos",
    "cheira papel novo com verdadeiro prazer",
  ],
  fears: [
    "perder a visão",
    "uma assinatura borrada",
    "a umidade e o que ela faz ao papel",
    "ser substituíd{o|a} por uma prensa de impressão",
  ],
  secrets: [
    "Falsifica documentos por fora.",
    "Leu uma carta que não devia e sabe de algo perigoso.",
    "Acrescentou o próprio nome aos registros de uma família nobre.",
    "Guarda uma cópia de cada carta secreta que já escreveu.",
  ],
};
