import type { BackgroundTables } from "../../backgrounds/types";

export const soldier: BackgroundTables = {
  garment: [
    "um casaco militar desbotado",
    "um gibão acolchoado surrado",
    "uma cota de malha sob uma capa de viagem",
    "uma túnica de regimento com a insígnia arrancada",
    "uma armadura de couro gasta",
    "uma armadura de placas desencontrada de mercenário",
    "um colete verde de arqueiro",
    "um casaco de cavalaria com botões de latão",
    "um uniforme de gala de veterano, que já não serve direito",
    "o casaco sensato de um intendente",
  ],
  accessory: [
    "uma velha cicatriz no rosto",
    "uma espada de lâmina entalhada",
    "uma medalha mantida polida",
    "uma manqueira de um ferimento antigo",
    "a lembrança de um amigo morto, presa a um cordão",
    "um escudo com o brasão pintado por cima",
    "um arco e uma aljava pela metade",
    "uma orelha faltando",
    "botas que marcharam mil milhas",
    "um livro de soldo militar, ainda sem pagamento",
  ],
  wants: [
    "Quer entregar a {relation} a última carta de um camarada morto.",
    "Tem soldo atrasado a receber e o quer {deadline}.",
    "Quer encontrar o oficial que abandonou sua unidade.",
    "Quer um trabalho tranquilo, onde ninguém grite ordens.",
    "Quer treinar alguém, para que as velhas habilidades sirvam para alguma coisa.",
    "Precisa se apresentar ao antigo comandante {deadline} e morre de medo disso.",
    "Quer encontrar o estandarte perdido do velho regimento, visto pela última vez {place}.",
    "Quer visitar os túmulos da sua unidade antes que a estação acabe.",
    "Precisa de trabalho como espada de aluguel {deadline}.",
    "Quer limpar o próprio nome de uma acusação de covardia.",
    "Quer abrir uma taverna para veteranos.",
    "Quer saber se a guerra acabou mesmo e não confia na resposta.",
  ],
  quirks: [
    "acorda antes do amanhecer e não consegue evitar",
    "bate continência a oficiais por hábito, até aos estrangeiros",
    "afia a lâmina quando está pensando",
    "come depressa, como se a ordem de marchar pudesse vir a qualquer momento",
  ],
  fears: ["barulhos altos à noite", "outra guerra", "os rostos que vê nos sonhos", "se tornar inútil"],
  secrets: [
    "Desertou antes da última batalha.",
    "Levou o crédito pela bravura de outro soldado.",
    "Poupou um inimigo que depois se tornou senhor da guerra.",
    "Já lutou pelo outro lado.",
  ],
};
