import type { BackgroundTables } from "../../backgrounds/types";

export const wayfarer: BackgroundTables = {
  garment: [
    "uma capa gasta pela estrada",
    "roupas em camadas, de muitos lugares",
    "um casaco com capuz e remendos desencontrados",
    "uma camisa desbotada pelo sol e botas de viagem",
    "uma capa com uma dúzia de insígnias de cidades distantes presas nela",
    "um poncho de tecido estrangeiro",
    "um manto cinza de peregrino",
    "um casaco de muitos bolsos, todos cheios",
    "trapos de mendigo com botas finas",
    "um colete de caçador ganho num jogo de cartas",
  ],
  accessory: [
    "uma mochila pesada",
    "um rolo de cama amarrado em cima",
    "um cajado de madeira polida",
    "uma bolsinha de bugigangas de cada cidade",
    "uma caneca de lata amassada pendurada num cordão",
    "uma mula pequena chamada por um nome pomposo",
    "um maço de cartas nunca respondidas",
    "um par de dados bem gastos",
    "uma lanterna chacoalhando na cintura",
    "um mapa coberto de anotações próprias",
  ],
  wants: [
    "Quer uma cama quente e uma refeição farta {deadline}.",
    "Procura {relation}, que deixou um bilhete marcando encontro {place}.",
    "Quer chegar a uma cidade distante antes que o inverno feche os desfiladeiros.",
    "Quer trocar uma história por uma carona na carroça de alguém.",
    "Quer encontrar um lugar onde se sinta em casa.",
    "Quer saber se os boatos sobre o que há {place} são verdadeiros.",
    "Precisa pagar um pedágio {deadline} e só tem {item} para oferecer.",
    "Quer ver a famosa cachoeira de que todo mundo fala.",
    "Quer um companheiro de viagem que não fale demais.",
    "Quer encontrar a estrada que um dos avós percorreu um dia.",
    "Quer entregar um pacote para um desconhecido e já começa a se arrepender.",
    "Quer dormir dois dias seguidos.",
  ],
  quirks: [
    "tem uma história para cada cidade",
    "nunca passa duas noites na mesma cama",
    "dorme melhor no chão do que numa cama",
    "coleciona ditados locais e os usa errado",
  ],
  fears: [
    "ficar tempo demais num só lugar",
    "o fim da estrada",
    "ser esquecid{o|a} por todos que conheceu",
    "um lar que não consiga deixar",
  ],
  secrets: [
    "Foge de algo que se recusa a nomear.",
    "Nasceu nesta mesma cidade.",
    "Carrega uma mensagem que nunca leu.",
    "É {um herdeiro exilado|uma herdeira exilada}, e a estrada é o único lugar seguro.",
  ],
};
