/**
 * Word lists every background draws from. Background files add their own
 * `quirks`, `fears` and `secrets` on top of these, and may use any slot here.
 * Pronoun slots ({they}, {their}, {them}, {theirs}, {themself}) come from the
 * character's gender; write verbs in the singular ("needs", "hides").
 */
export const SHARED_TABLES = {
  condition: [
    "well kept",
    "travel-stained",
    "patched in a few places",
    "a size too large",
    "freshly laundered",
    "faded by the sun",
    "worn thin at the elbows",
    "smelling faintly of woodsmoke",
    "better than {they} can obviously afford",
    "muddy to the knees",
    "carefully mended",
    "suspiciously clean",
    "a size too small",
    "still damp from last night's rain",
    "creased from being slept in",
    "mended with thread of the wrong colour",
    "older than {they} is",
    "spotless, which seems to take real effort",
    "dusty from the road",
    "torn at the hem",
    "scented with cheap perfume",
    "in surprisingly good taste",
  ],
  relation: [
    "a cousin",
    "the miller's son",
    "an old army friend",
    "a debt collector",
    "a former lover",
    "the local priest",
    "a travelling tinker",
    "{their} older sister",
    "{their} younger brother",
    "a retired adventurer",
    "the innkeeper",
    "a guard captain",
    "a halfling peddler",
    "a childhood rival",
    "a widow from the next village",
    "a very persuasive stranger",
    "the blacksmith's apprentice",
    "an elderly aunt",
    "a dwarven moneylender",
    "the baker next door",
    "a hedge wizard",
    "{their} former employer",
    "a one-eyed fisherman",
    "a gnome inventor",
    "the village elder",
    "a cloaked figure who never gave a name",
    "a tiefling card dealer",
    "{their} best friend's spouse",
  ],
  deadline: [
    "before sundown",
    "by the next market day",
    "before the harvest festival",
    "before the first snow",
    "before the end of the week",
    "before the tax collector arrives",
    "by the next full moon",
    "before anyone notices",
    "today, ideally an hour ago",
    "before the wedding",
    "before the caravan leaves",
    "before {their} mother finds out",
    "by tomorrow morning",
    "before the bridge is closed",
    "before the rains come",
    "before the funeral",
    "by midsummer",
    "before the duke's visit",
    "before the tide turns",
    "before {they} loses {their} nerve",
    "before the bell tolls midnight",
    "before the guild meeting",
  ],
  timeAgo: [
    "three days ago",
    "last winter",
    "since the flood",
    "a fortnight ago",
    "on the night of the storm",
    "two harvests ago",
    "the morning after the festival",
    "yesterday, which was a mistake",
    "last spring",
    "a month ago",
    "during the eclipse",
    "after a long night of drinking",
    "the day the old king died",
    "seven years ago",
    "at the last market",
    "this very morning",
  ],
  item: [
    "a silver locket",
    "the deed to a small farm",
    "a sealed letter",
    "an iron key with no lock",
    "a lucky copper coin",
    "a map with half the names scratched out",
    "a bone-handled knife",
    "a ring too fine for {them}",
    "a jar of very rare honey",
    "a book with a broken clasp",
    "a pressed flower in an envelope",
    "a pouch of foreign coins",
    "a carved wooden bird",
    "a family signet",
    "a cracked hand mirror",
    "a music box that plays one sad tune",
    "a dragon's tooth, or so {they} claims",
    "a velvet pouch of loose gems",
    "a child's drawing",
    "a vial of something that glows faintly",
    "an unpaid promissory note",
    "a lock of someone's hair",
    "a sword hilt without a blade",
    "a tarnished medal",
    "a stuffed owl",
    "a recipe for a very old wine",
    "a brass compass that points south",
    "a portrait of a stranger",
  ],
  place: [
    "the old mill",
    "the harbor",
    "the next town over",
    "the temple district",
    "a roadside shrine",
    "the king's road",
    "the tavern cellar",
    "the marsh",
    "the ruined watchtower",
    "the market square",
    "the forest edge",
    "the graveyard on the hill",
    "the abandoned mine",
    "the crossroads gallows",
    "the old stone bridge",
    "the bathhouse",
    "the duke's gardens",
    "a smugglers' cove",
    "the standing stones",
    "the lighthouse",
    "the fairgrounds",
    "the sewers under the city",
    "a hunting lodge in the hills",
    "the flooded chapel",
  ],
  quirks: [
    "hums the same three notes when thinking",
    "never sits with {their} back to a door",
    "counts coins twice, then a third time to be sure",
    "names every animal {they} meets",
    "taps the table before every meal for luck",
    "speaks to strangers as if they were old friends",
    "collects buttons and keeps the best ones in a tin",
    "laughs a beat too late at every joke",
    "always knows which way is north",
    "refuses to say the name of the moon out loud",
    "sniffs food carefully before eating it",
    "keeps a running list of everyone who owes {them} a favour",
    "whistles badly but often",
    "quotes proverbs, mostly made up",
    "cannot pass a stray cat without stopping",
    "rolls a coin across {their} knuckles when nervous",
    "apologizes to furniture after bumping into it",
    "carries {item} everywhere and touches it when lying",
    "insists on being called by a nickname nobody uses",
    "sleeps with {their} boots on",
    "finishes other people's sentences, usually wrongly",
    "eats dessert first, as a matter of principle",
    "keeps a pebble from every town {they} visits",
    "talks in the third person when angry",
    "cracks {their} knuckles before any decision",
    "cannot keep a secret for more than a day",
    "salts everything before tasting it",
    "gives everyone a nickname within a minute of meeting them",
    "is always slightly cold",
    "writes {their} name on everything {they} owns",
    "tells the same story three times a night",
    "stops to read every notice board",
    "carries a spoon at all times, just in case",
    "only ever sits in corners",
    "laughs loudly at funerals out of nerves",
    "keeps an eye on the weather at all times, even indoors",
    "uses words {they} doesn't quite know the meaning of",
    "gets lost in thought mid-conversation",
    "refuses to step on cracks in the road",
    "always pays a little too much, and mentions it",
  ],
  fears: [
    "deep water",
    "being forgotten",
    "closed spaces and the dark inside them",
    "owls, for reasons {they} won't explain",
    "growing old alone",
    "fire, ever since the night {their} home burned",
    "letting {their} family down",
    "magic {they} can't understand",
    "debt",
    "the sound of bells at night",
    "being seen crying",
    "heights, especially bridges",
    "dogs larger than a bread loaf",
    "that {relation} will come back",
    "dying somewhere nobody will find {them}",
    "being recognized from {their} past",
    "spiders, all of them, of every size",
    "the undead, after what happened at {place}",
    "being poor again",
    "mirrors at night",
    "thunderstorms",
    "being laughed at",
    "the sea",
    "sickness and the people who carry it",
    "being trapped in a crowd",
    "that {they} is turning into {their} father",
    "that {they} is turning into {their} mother",
    "elves, whom {they} finds unsettling",
    "silence",
    "going blind",
    "being buried alive",
    "making a choice that cannot be undone",
  ],
  secrets: [
    "{They} is not using {their} real name.",
    "{They} still has {item}, which {they} swore was lost.",
    "{They} owes a dangerous amount of money to {relation}.",
    "{They} once left a friend behind at {place} and never told anyone.",
    "{They} can read, and hides it.",
    "{They} has a child in another town that nobody knows about.",
    "{They} sold out {relation} for a handful of silver years ago.",
    "{They} is terrified of the very thing {they} is famous for.",
    "{They} buried something at {place} and goes back to check on it.",
    "{They} writes letters to a dead parent and burns them.",
    "{They} is secretly very wealthy and dresses down on purpose.",
    "{They} witnessed a murder at {place} and kept quiet.",
    "{They} was once a member of a cult and still knows the passwords.",
    "{They} has never actually seen the sea, despite all the stories.",
    "{They} is in love with {relation}, who has no idea.",
    "{They} stole {item} from {relation} {timeAgo}.",
    "{They} has a twin who is wanted by the law.",
    "{They} is being blackmailed by {relation}.",
    "{They} can hear whispers from {item}, and listens to them.",
    "{They} faked {their} own death once and might do it again.",
    "{They} has been spying on the town for someone far away.",
    "{They} was once engaged to royalty, briefly.",
    "{They} cannot swim, and lies about it constantly.",
    "{They} started the fire at {place} {timeAgo}.",
    "{They} has a hidden stash of coins at {place}.",
    "{They} made a bargain with a fey creature and still owes it a favour.",
    "{They} is older than {they} looks, much older.",
    "{They} took the blame for {relation}'s crime, and regrets it.",
  ],
  /** Used when no background is chosen. */
  wants: [
    "{They} wants {their} share of an inheritance from {relation} {deadline}.",
    "{They} lost {item} near {place} and wants it back {deadline}.",
    "{They} wants a quiet life and keeps not getting one.",
    "{They} needs someone to carry a message to {relation} {deadline}.",
    "{They} wants to leave town {deadline} without anyone asking why.",
    "{They} is looking for work, any work, {deadline}.",
    "{They} wants to find out who keeps leaving flowers on {their} doorstep.",
    "{They} needs a witness to swear {they} was at {place} {timeAgo}.",
    "{They} wants to sell {item}, no questions asked.",
    "{They} wants an apology from {relation}, in public.",
    "{They} wants to win a bet {they} made {timeAgo}, whatever it takes.",
    "{They} needs to borrow a horse {deadline} and has nothing to offer for it.",
  ],
} as const;
