/**
 * Listas de palavras pt-BR que todas as origens usam. Os arquivos de origem
 * somam seus próprios `quirks`, `fears` e `secrets` a estas e podem usar
 * qualquer slot daqui. Regras: nada de pronomes ingleses; o sujeito é omitido
 * e o que concorda com o gênero do personagem vai em `{masculino|feminino}`;
 * `relation` e `item` levam artigo indefinido ou possessivo; `place` é uma
 * locução locativa com preposição própria; `condition` concorda com "a roupa".
 */
export const PT_SHARED_TABLES = {
  condition: [
    "bem cuidada",
    "manchada da viagem",
    "remendada em alguns lugares",
    "grande demais para {ele|ela}",
    "recém-lavada",
    "desbotada pelo sol",
    "gasta nos cotovelos",
    "com um leve cheiro de fumaça de lenha",
    "melhor do que {ele|ela} claramente pode pagar",
    "enlameada até os joelhos",
    "cuidadosamente remendada",
    "suspeitosamente limpa",
    "pequena demais para {ele|ela}",
    "ainda úmida da chuva de ontem à noite",
    "amassada de tanto dormir com ela",
    "remendada com linha da cor errada",
    "mais velha do que {ele|ela}",
    "impecável, o que parece dar muito trabalho",
    "empoeirada da estrada",
    "rasgada na barra",
    "perfumada com perfume barato",
    "de um bom gosto surpreendente",
  ],
  relation: [
    "um primo",
    "um filho de moleiro",
    "um velho amigo de guerra",
    "um cobrador de dívidas",
    "um antigo amor",
    "um padre da região",
    "um funileiro viajante",
    "sua irmã mais velha",
    "seu irmão mais novo",
    "um aventureiro aposentado",
    "um estalajadeiro",
    "um capitão da guarda",
    "um mascate halfling",
    "um rival de infância",
    "uma viúva da aldeia vizinha",
    "um desconhecido muito persuasivo",
    "um aprendiz de ferreiro",
    "uma tia idosa",
    "um agiota anão",
    "um padeiro vizinho",
    "um mago de beira de estrada",
    "seu antigo patrão",
    "um pescador de um olho só",
    "um inventor gnomo",
    "um ancião da aldeia",
    "uma figura encapuzada que nunca disse o nome",
    "um carteador tiefling",
    "uma pessoa casada com seu melhor amigo",
  ],
  deadline: [
    "antes do pôr do sol",
    "até o próximo dia de feira",
    "antes do festival da colheita",
    "antes da primeira neve",
    "antes do fim da semana",
    "antes que o coletor de impostos chegue",
    "até a próxima lua cheia",
    "antes que alguém perceba",
    "hoje, de preferência há uma hora",
    "antes do casamento",
    "antes que a caravana parta",
    "antes que a mãe {dele|dela} descubra",
    "até amanhã de manhã",
    "antes que a ponte seja fechada",
    "antes que as chuvas cheguem",
    "antes do funeral",
    "até o meio do verão",
    "antes da visita do duque",
    "antes que a maré vire",
    "antes que lhe falte a coragem",
    "antes que o sino bata meia-noite",
    "antes da reunião da guilda",
  ],
  timeAgo: [
    "há três dias",
    "no inverno passado",
    "na época da enchente",
    "há quinze dias",
    "na noite da tempestade",
    "há duas colheitas",
    "na manhã seguinte ao festival",
    "ontem, o que foi um erro",
    "na primavera passada",
    "há um mês",
    "durante o eclipse",
    "depois de uma longa noite de bebedeira",
    "no dia em que o velho rei morreu",
    "há sete anos",
    "na última feira",
    "hoje de manhã mesmo",
  ],
  item: [
    "um medalhão de prata",
    "uma escritura de um pequeno sítio",
    "uma carta lacrada",
    "uma chave de ferro sem fechadura",
    "uma moeda de cobre da sorte",
    "um mapa com metade dos nomes riscados",
    "uma faca de cabo de osso",
    "um anel fino demais para {ele|ela}",
    "um pote de mel raríssimo",
    "um livro com o fecho quebrado",
    "uma flor prensada num envelope",
    "uma bolsinha de moedas estrangeiras",
    "um passarinho de madeira entalhada",
    "um sinete de família",
    "um espelhinho de mão rachado",
    "uma caixa de música que toca uma única melodia triste",
    "um dente de dragão, ao que {ele|ela} diz",
    "uma bolsa de veludo com pedras soltas",
    "um desenho de criança",
    "um frasco de algo que brilha de leve",
    "uma nota promissória não paga",
    "um cacho de cabelo de alguém",
    "um punho de espada sem lâmina",
    "uma medalha embaçada",
    "uma coruja empalhada",
    "uma receita de um vinho muito antigo",
    "uma bússola de latão que aponta para o sul",
    "um retrato de um desconhecido",
  ],
  place: [
    "no velho moinho",
    "no porto",
    "na cidade vizinha",
    "no distrito dos templos",
    "num santuário à beira da estrada",
    "na estrada real",
    "no porão da taverna",
    "no pântano",
    "na torre de vigia em ruínas",
    "na praça do mercado",
    "à beira da floresta",
    "no cemitério da colina",
    "na mina abandonada",
    "na forca da encruzilhada",
    "na velha ponte de pedra",
    "nas termas",
    "nos jardins do duque",
    "numa enseada de contrabandistas",
    "nas pedras eretas",
    "no farol",
    "no parque da feira",
    "nos esgotos sob a cidade",
    "num pavilhão de caça nas colinas",
    "na capela alagada",
  ],
  quirks: [
    "cantarola as mesmas três notas quando pensa",
    "nunca se senta de costas para uma porta",
    "conta as moedas duas vezes, e uma terceira para ter certeza",
    "dá nome a todo animal que encontra",
    "bate na mesa antes de cada refeição, para dar sorte",
    "fala com estranhos como se fossem velhos amigos",
    "coleciona botões e guarda os melhores numa lata",
    "ri um instante tarde demais de toda piada",
    "sempre sabe onde fica o norte",
    "se recusa a dizer o nome da lua em voz alta",
    "cheira a comida com cuidado antes de comer",
    "mantém uma lista de todos que lhe devem um favor",
    "assobia mal, mas com frequência",
    "cita provérbios, quase todos inventados",
    "não consegue passar por um gato de rua sem parar",
    "gira uma moeda entre os dedos quando está nervos{o|a}",
    "pede desculpas aos móveis depois de esbarrar neles",
    "carrega {item} por toda parte e mexe nisso quando mente",
    "insiste em ser chamad{o|a} por um apelido que ninguém usa",
    "dorme de botas",
    "termina as frases dos outros, geralmente errado",
    "come a sobremesa primeiro, por princípio",
    "guarda uma pedrinha de cada cidade que visita",
    "fala de si na terceira pessoa quando está com raiva",
    "estala os dedos antes de qualquer decisão",
    "não consegue guardar um segredo por mais de um dia",
    "salga tudo antes de provar",
    "dá um apelido a todo mundo um minuto depois de conhecê-lo",
    "está sempre com um pouco de frio",
    "escreve o próprio nome em tudo que possui",
    "conta a mesma história três vezes por noite",
    "para para ler todos os quadros de avisos",
    "anda sempre com uma colher, só por precaução",
    "só se senta em cantos",
    "ri alto em funerais, de nervoso",
    "vigia o tempo o tempo todo, até dentro de casa",
    "usa palavras cujo significado não conhece direito",
    "se perde em pensamentos no meio da conversa",
    "se recusa a pisar nas rachaduras da estrada",
    "sempre paga um pouco a mais, e faz questão de mencionar",
  ],
  fears: [
    "água funda",
    "ser esquecid{o|a}",
    "espaços fechados e o escuro que há neles",
    "corujas, por motivos que não explica",
    "envelhecer sozinh{o|a}",
    "fogo, desde a noite em que sua casa pegou fogo",
    "decepcionar a família",
    "magia que não consegue entender",
    "dívidas",
    "o som de sinos à noite",
    "ser vist{o|a} chorando",
    "altura, principalmente pontes",
    "cães maiores que um pão",
    "que {relation} volte",
    "morrer num lugar onde ninguém {o|a} encontre",
    "ser reconhecid{o|a} por causa do passado",
    "aranhas, todas elas, de qualquer tamanho",
    "os mortos-vivos, depois do que aconteceu {place}",
    "voltar a ser pobre",
    "espelhos à noite",
    "tempestades",
    "ser alvo de riso",
    "o mar",
    "doenças e quem as carrega",
    "ficar pres{o|a} no meio da multidão",
    "estar ficando igual ao pai",
    "estar ficando igual à mãe",
    "elfos, que acha perturbadores",
    "o silêncio",
    "ficar cego",
    "ser enterrad{o|a} viv{o|a}",
    "fazer uma escolha que não pode ser desfeita",
  ],
  secrets: [
    "Não usa o próprio nome verdadeiro.",
    "Ainda tem {item}, que jurou ter perdido.",
    "Deve uma quantia perigosa a {relation}.",
    "Um dia abandonou um amigo {place} e nunca contou a ninguém.",
    "Sabe ler e esconde isso.",
    "Tem um filho em outra cidade de que ninguém sabe.",
    "Entregou {relation} por um punhado de prata anos atrás.",
    "Morre de medo justamente daquilo pelo que é famos{o|a}.",
    "Enterrou algo {place} e volta lá para conferir.",
    "Escreve cartas para um dos pais, já falecido, e as queima.",
    "É secretamente muito ric{o|a} e se veste mal de propósito.",
    "Presenciou um assassinato {place} e ficou calad{o|a}.",
    "Já foi membro de um culto e ainda sabe as senhas.",
    "Nunca viu o mar de verdade, apesar de todas as histórias.",
    "É apaixonad{o|a} por {relation}, que nem desconfia.",
    "Roubou {item} de {relation} {timeAgo}.",
    "Tem um gêmeo procurado pela lei.",
    "Está sendo chantagead{o|a} por {relation}.",
    "Ouve sussurros vindos de {item} e dá ouvidos a eles.",
    "Já forjou a própria morte e talvez faça isso de novo.",
    "Espiona a cidade para alguém muito distante.",
    "Já foi noiv{o|a} de alguém da realeza, por pouco tempo.",
    "Não sabe nadar e mente sobre isso o tempo todo.",
    "Começou o incêndio {place} {timeAgo}.",
    "Tem um esconderijo de moedas {place}.",
    "Fez um trato com uma criatura feérica e ainda lhe deve um favor.",
    "É mais velh{o|a} do que parece, muito mais.",
    "Assumiu a culpa pelo crime de {relation} e se arrepende disso.",
  ],
  /** Usado quando nenhuma origem é escolhida. */
  wants: [
    "Quer a sua parte da herança de {relation} {deadline}.",
    "Perdeu {item} {place} e quer isso de volta {deadline}.",
    "Quer uma vida tranquila e não consegue ter uma.",
    "Precisa de alguém que leve um recado a {relation} {deadline}.",
    "Quer sair da cidade {deadline} sem que ninguém pergunte por quê.",
    "Procura trabalho, qualquer trabalho, {deadline}.",
    "Quer descobrir quem anda deixando flores na porta de sua casa.",
    "Precisa de uma testemunha que jure que esteve {place} {timeAgo}.",
    "Quer vender {item}, sem perguntas.",
    "Quer um pedido de desculpas de {relation}, em público.",
    "Quer ganhar uma aposta feita {timeAgo}, custe o que custar.",
    "Precisa pegar um cavalo emprestado {deadline} e não tem nada a oferecer em troca.",
  ],
} as const;
