import type { NarrativeLocale } from "./types";

/**
 * English summary phrases. Each table is named `<group>_<Value>`, the value
 * with its spaces and punctuation dropped (see slotKey). `cond_*` entries
 * carry the article ("a", "an") because they open the noun phrase.
 */
export const EN_NARRATIVE: NarrativeLocale = {
  templates: [
    "{name} is {cond} {purpose} {type} {geo}.",
    "It was founded {detail}, {age}.",
    "{growth}",
    "{change}",
    "{prosperity} {tone}",
  ],
  masculineTypes: [],
  tables: {
    cond_Growing: ["a growing", "a thriving"],
    cond_Stable: ["a steady", "a long-settled"],
    cond_Declining: ["a declining", "a fading"],
    cond_Recovering: ["a recovering", "a slowly recovering"],
    cond_Overcrowded: ["an overcrowded", "a crowded, bursting"],
    cond_PartlyAbandoned: ["a half-empty", "a half-abandoned"],
    cond_Rebuilding: ["a rebuilding", "a half-rebuilt"],

    purpose_Farming: ["farming"],
    purpose_Herding: ["herding"],
    purpose_Fishing: ["fishing"],
    purpose_Mining: ["mining"],
    purpose_Logging: ["logging"],
    purpose_Hunting: ["hunting"],
    purpose_Trade: ["trading"],
    purpose_Port: ["port"],
    purpose_Military: ["garrison"],
    purpose_Religious: ["temple"],
    purpose_Scholarly: ["scholarly"],
    purpose_Crafting: ["artisan"],
    purpose_Administrative: ["administrative"],
    purpose_Refuge: ["refugee"],
    purpose_Smuggling: ["smugglers'"],
    purpose_Leisure: ["pleasure"],

    type_Homestead: ["homestead"],
    type_Hamlet: ["hamlet"],
    type_Village: ["village"],
    type_Town: ["town"],
    type_City: ["city"],
    type_Metropolis: ["metropolis"],
    type_Encampment: ["camp"],

    geo_Coast: ["on a windswept coast", "looking out over the sea"],
    geo_Riverbank: ["on the banks of a wide river", "beside a slow, muddy river"],
    geo_LakeShore: ["on the shore of a broad lake", "beside a still lake"],
    geo_Plains: ["on open plains", "amid rolling grassland"],
    geo_Hills: ["among rolling hills", "on top of a hill"],
    geo_Mountains: ["high in the mountains", "clinging to a mountainside"],
    geo_Island: ["on a small island", "on a rocky island"],
    geo_Underground: ["deep beneath the earth", "inside a vast cavern"],
    geo_Forest: ["deep in the forest", "in a clearing of an old forest"],
    geo_Swamp: ["in the middle of a swamp", "on stilts above a marsh"],
    geo_Desert: ["in the open desert", "among the dunes"],
    geo_Valley: ["in a sheltered valley", "at the bottom of a deep valley"],
    geo_RiverDelta: ["where a great river meets the sea", "among the channels of a river delta"],
    geo_Canyon: ["inside a narrow canyon", "carved into the walls of a canyon"],
    geo_Volcanic: ["on the slopes of a volcano", "in the shadow of a smoking volcano"],
    geo_Tundra: ["on the frozen tundra", "on an icy plain"],
    geo_Oasis: ["around a desert oasis", "among the palms of an oasis"],
    geo_Steppe: ["on the endless steppe", "on wind-scoured grassland"],

    detail_ShallowFord: ["beside a shallow ford"],
    detail_AncientBridge: ["at the foot of an ancient bridge"],
    detail_FerryCrossing: ["at a ferry crossing"],
    detail_MountainPass: ["to guard a mountain pass"],
    detail_DeepBay: ["on a deep natural bay"],
    detail_HiddenCove: ["in a hidden cove"],
    detail_RiverMouth: ["at the mouth of a river"],
    detail_ShelteredInlet: ["on a sheltered inlet"],
    detail_Silver: ["around a rich silver vein"],
    detail_Iron: ["beside deposits of iron ore"],
    detail_Gold: ["where gold was found in the rock"],
    detail_Copper: ["around a copper mine"],
    detail_Tin: ["over a seam of tin"],
    detail_Salt: ["beside rich salt deposits"],
    detail_Gems: ["where gemstones glittered in the rock"],
    detail_Coal: ["over a seam of coal"],
    detail_Marble: ["beside a marble quarry"],
    detail_Sulfur: ["around vents of yellow sulfur"],
    detail_Obsidian: ["on fields of black obsidian"],
    detail_Mithral: ["over a rare seam of mithral"],
    detail_BlackSoil: ["on rich black soil"],
    detail_FloodPlains: ["on flood-fed fields"],
    detail_TerracedSlopes: ["on slopes terraced for crops"],
    detail_OrchardsandGroves: ["among fruit orchards and groves"],
    detail_AshRichSoil: ["on soil made rich by volcanic ash"],
    detail_FungalCaverns: ["beside caverns where edible fungi grow"],
    detail_DatePalms: ["among groves of date palms"],
    detail_SacredSpring: ["around a sacred spring"],
    detail_StandingStones: ["beside a ring of ancient standing stones"],
    detail_SiteofaMiracle: ["where a miracle was witnessed"],
    detail_SaintsTomb: ["around a saint's tomb"],
    detail_FallenStar: ["where a star fell from the sky"],
    detail_FireMountain: ["to worship the fire of the mountain"],
    detail_BorderKeep: ["around a border keep"],
    detail_HilltopFort: ["below a hilltop fort"],
    detail_Watchtower: ["around a lonely watchtower"],
    detail_LegionCamp: ["on the site of an old legion camp"],
    detail_TradeRoads: ["where two trade roads meet"],
    detail_CaravanRoute: ["as a stop on a caravan route"],
    detail_PilgrimRoad: ["as a rest stop on a pilgrim road"],
    detail_RiverJunction: ["where two rivers join"],
    detail_TunnelJunction: ["where great tunnels cross"],
    detail_War: ["by families fleeing a war"],
    detail_Persecution: ["by people fleeing persecution"],
    detail_Plague: ["by survivors fleeing a plague"],
    detail_NaturalDisaster: ["by survivors of a great disaster"],
    detail_Monsters: ["by folk driven from their homes by monsters"],
    detail_GreatHerds: ["to follow the great herds"],
    detail_DeepWoods: ["at the edge of deep, game-rich woods"],
    detail_FurRichWilds: ["to trap the fur-rich wilds"],
    detail_TeemingWaters: ["beside waters teeming with fish"],
    detail_CaveBeasts: ["to hunt the beasts of the deep caves"],
    detail_ElvenRuins: ["among elven ruins"],
    detail_DwarvenHold: ["in an abandoned dwarven hold"],
    detail_FallenEmpire: ["among the ruins of a fallen empire"],
    detail_ForgottenTemple: ["around a forgotten temple"],
    detail_GiantsRuin: ["in the ruins left by giants"],
    detail_FreshSpring: ["around a freshwater spring"],
    detail_HotSprings: ["around steaming hot springs"],
    detail_DeepWell: ["around a deep well"],
    detail_RoyalCharter: ["by royal charter"],
    detail_TempleDecree: ["by decree of a temple"],
    detail_GuildCharter: ["under a guild charter"],
    detail_PenalColony: ["as a penal colony"],

    age_Recent: ["only a few years ago", "within living memory"],
    age_Generations: ["a few generations ago", "in the days of its elders' grandparents"],
    age_Centuries: ["centuries ago", "several hundred years ago"],
    age_Ancient: ["so long ago that no one remembers its founders", "in an age older than any chronicle"],
    age_BuiltOverRuins: ["on the foundations of a far older town", "over the ruins of an older settlement"],
    age_RuinsReused: ["its first houses raised from the fallen stones", "with stones taken from what came before"],

    growth_Planned: ["It was laid out to a plan from the first stone, and it still shows.", "Everything was measured and marked out before the first roof went up."],
    growth_Gradual: ["It grew slowly, one roof and one field at a time.", "Nobody planned it; it simply grew, year after year."],
    growth_Migration: ["A sudden wave of newcomers swelled it faster than anyone expected.", "It filled almost overnight when settlers came pouring in."],
    growth_Occupation: ["Soldiers held it before settlers did, and the garrison shaped everything.", "It grew around an occupying force that never quite left."],
    growth_Merged: ["It is really several older communities that grew into one another.", "Neighboring settlements slowly merged into it, and old rivalries survive."],
    growth_BoomandBust: ["It has boomed and emptied more than once, following its fortunes.", "Its fortunes have risen and crashed again and again."],

    change_NewRuler: ["A new ruler has just taken charge, and no one yet knows what to expect.", "Power recently changed hands, and old loyalties are being tested."],
    change_FailedHarvest: ["The last harvest failed, and hunger is setting in.", "Blight ruined this year's crops, and stores are running low."],
    change_ReopenedMine: ["An old mine has just reopened, bringing work and newcomers.", "Miners recently broke into a fresh vein, and hope is returning."],
    change_ExhaustedMine: ["The mine has all but run dry, and families are drifting away.", "The last good vein was exhausted, and the work has gone with it."],
    change_DestroyedBridge: ["The bridge that tied it to the world was recently destroyed.", "Its bridge collapsed not long ago, cutting the main road."],
    change_Refugees: ["Refugees have been arriving in numbers, straining everything.", "Strangers fleeing trouble elsewhere keep arriving, and tempers are short."],
    change_Discovery: ["Something strange was discovered nearby, and rumors are spreading.", "A recent discovery nearby has drawn curious and dangerous visitors."],
    change_Plague: ["A sickness is spreading through its homes.", "A fever has taken hold, and the healers cannot keep up."],
    change_NewTradeRoute: ["A new trade route has started bringing merchants through.", "Merchants have only recently begun passing this way, with coin and news."],
    change_LostTradeRoute: ["The trade that once passed through has moved elsewhere.", "The caravans and merchants stopped coming, and the money went with them."],
    change_Monsters: ["Monsters have been sighted closer than ever.", "Something has been killing livestock at night, and no one has seen it clearly."],
    change_Schism: ["Its faithful have split over a bitter dispute of doctrine.", "A quarrel among the priests has set neighbor against neighbor."],
    change_Fire: ["A fire recently tore through part of it.", "Not long ago a fire left part of it a blackened shell."],
    change_Flood: ["Floodwaters recently swept through its lower ground.", "A recent flood left mud, ruin and debts behind."],
    change_Raid: ["Raiders struck it not long ago, and the scars are fresh.", "A recent raid cost lives and goods, and everyone fears the next one."],
    change_Disappearances: ["People have been vanishing without a trace.", "Several people have disappeared lately, and no one will talk about it."],
    change_Crackdown: ["Its rulers have just imposed harsh new laws.", "A recent crackdown filled the cells, and informers are everywhere."],
    change_Festival: ["Everyone is busy preparing for a great festival.", "A festival is coming, and the place is full of preparations and visitors."],
    change_Windfall: ["A sudden windfall has filled some purses and stirred plenty of envy.", "Unexpected wealth recently arrived, and everyone wants a share."],
    change_Eruption: ["The volcano recently woke, raining ash over everything.", "A recent eruption buried fields and homes under ash."],

    prosperity_Destitute: ["Most of its people barely survive from one day to the next."],
    prosperity_Poor: ["Most of its people scrape by on very little."],
    prosperity_Modest: ["Its people get by, neither rich nor poor."],
    prosperity_Comfortable: ["Its people live comfortably, and it shows in their homes."],
    prosperity_Wealthy: ["Its people live well, with coin to spare."],
    prosperity_ExceptionallyRich: ["Its people live in a luxury few elsewhere could imagine."],

    tone_Peaceful: ["Life here is calm, and neighbors look out for one another.", "Quarrels are rare, and doors are seldom locked."],
    tone_Lively: ["There is always noise, music and gossip somewhere.", "Its people love a celebration, a bargain and a good story."],
    tone_Harsh: ["Life here is hard, and only the tough last.", "Nothing comes easy here, and nobody expects it to."],
    tone_Grim: ["Few smile here, and fewer hope.", "An air of gloom hangs over everything."],
    tone_Mysterious: ["Locals keep their secrets, and strangers feel watched.", "Odd customs and quiet glances hint at things left unsaid."],
    tone_Decadent: ["Wealth and vice mix openly, and everything has a price.", "Its pleasures are many, and its scruples few."],
    tone_Oppressive: ["Those in charge watch closely, and people speak in whispers.", "Rules are many, punishments harsh, and complaints rare."],
  },
};
