import type { NarrativeLocale } from "./types";

/**
 * Frases pt-BR do resumo, com as mesmas tabelas do inglês. `type_*` traz o
 * artigo; o que concorda com o substantivo do tipo (sítio, vila, cidade…) vai
 * em `{masculino|feminino}`; os tipos masculinos estão em `masculineTypes`.
 */
export const PT_NARRATIVE: NarrativeLocale = {
  templates: [
    "{name} é {type} {purpose} {cond} {geo}.",
    "Foi {fundado|fundada} {detail}, {age}.",
    "{growth}",
    "{change}",
    "{prosperity} {tone}",
  ],
  masculineTypes: ["Homestead", "Hamlet", "Encampment"],
  tables: {
    cond_Growing: ["em crescimento", "em plena expansão"],
    cond_Stable: ["estável", "de vida tranquila e constante"],
    cond_Declining: ["em declínio", "em decadência"],
    cond_Recovering: ["em recuperação", "que tenta se reerguer"],
    cond_Overcrowded: ["{superlotado|superlotada}", "{abarrotado|abarrotada} de gente"],
    cond_PartlyAbandoned: ["{meio vazio|meio vazia}", "{meio abandonado|meio abandonada}"],
    cond_Rebuilding: ["em reconstrução", "{meio reconstruído|meio reconstruída}"],

    purpose_Farming: ["agrícola"],
    purpose_Herding: ["de pastores"],
    purpose_Fishing: ["{pesqueiro|pesqueira}"],
    purpose_Mining: ["{minerador|mineradora}"],
    purpose_Logging: ["{madeireiro|madeireira}"],
    purpose_Hunting: ["de caçadores"],
    purpose_Trade: ["comercial"],
    purpose_Port: ["{portuário|portuária}"],
    purpose_Military: ["de guarnição"],
    purpose_Religious: ["{religioso|religiosa}"],
    purpose_Scholarly: ["de estudiosos"],
    purpose_Crafting: ["de artesãos"],
    purpose_Administrative: ["{administrativo|administrativa}"],
    purpose_Refuge: ["de refugiados"],
    purpose_Smuggling: ["de contrabandistas"],
    purpose_Leisure: ["de prazeres"],

    type_Homestead: ["um sítio"],
    type_Hamlet: ["um lugarejo"],
    type_Village: ["uma vila"],
    type_Town: ["uma cidade pequena"],
    type_City: ["uma cidade"],
    type_Metropolis: ["uma metrópole"],
    type_Encampment: ["um acampamento"],

    geo_Coast: ["numa costa varrida pelo vento", "de frente para o mar"],
    geo_Riverbank: ["às margens de um rio largo", "à beira de um rio lento e barrento"],
    geo_LakeShore: ["às margens de um grande lago", "junto a um lago de águas paradas"],
    geo_Plains: ["em planícies abertas", "no meio de campos ondulantes"],
    geo_Hills: ["entre colinas ondulantes", "no alto de uma colina"],
    geo_Mountains: ["no alto das montanhas", "{agarrado|agarrada} à encosta de uma montanha"],
    geo_Island: ["numa pequena ilha", "numa ilha rochosa"],
    geo_Underground: ["nas profundezas da terra", "dentro de uma caverna imensa"],
    geo_Forest: ["no coração da floresta", "numa clareira de uma floresta antiga"],
    geo_Swamp: ["no meio de um pântano", "sobre palafitas num brejo"],
    geo_Desert: ["em pleno deserto", "entre as dunas"],
    geo_Valley: ["num vale abrigado", "no fundo de um vale profundo"],
    geo_RiverDelta: ["onde um grande rio encontra o mar", "entre os canais de um delta"],
    geo_Canyon: ["dentro de um cânion estreito", "{escavado|escavada} nas paredes de um cânion"],
    geo_Volcanic: ["na encosta de um vulcão", "à sombra de um vulcão fumegante"],
    geo_Tundra: ["na tundra congelada", "numa planície gelada"],
    geo_Oasis: ["em volta de um oásis no deserto", "entre as palmeiras de um oásis"],
    geo_Steppe: ["na estepe sem fim", "em campos varridos pelo vento"],

    detail_ShallowFord: ["junto a um vau raso"],
    detail_AncientBridge: ["ao pé de uma ponte antiga"],
    detail_FerryCrossing: ["numa travessia de balsa"],
    detail_MountainPass: ["para vigiar uma passagem nas montanhas"],
    detail_DeepBay: ["numa baía natural profunda"],
    detail_HiddenCove: ["numa enseada escondida"],
    detail_RiverMouth: ["na foz de um rio"],
    detail_ShelteredInlet: ["num braço de mar abrigado"],
    detail_Silver: ["em torno de um rico veio de prata"],
    detail_Iron: ["junto a jazidas de ferro"],
    detail_Gold: ["onde se encontrou ouro na rocha"],
    detail_Copper: ["em torno de uma mina de cobre"],
    detail_Tin: ["sobre um filão de estanho"],
    detail_Salt: ["junto a ricas jazidas de sal"],
    detail_Gems: ["onde pedras preciosas brilhavam na rocha"],
    detail_Coal: ["sobre um filão de carvão"],
    detail_Marble: ["junto a uma pedreira de mármore"],
    detail_Sulfur: ["em torno de fendas de enxofre amarelo"],
    detail_Obsidian: ["sobre campos de obsidiana negra"],
    detail_Mithral: ["sobre um raro filão de mithral"],
    detail_BlackSoil: ["em terra preta e fértil"],
    detail_FloodPlains: ["em campos adubados pelas cheias"],
    detail_TerracedSlopes: ["em encostas cortadas em terraços"],
    detail_OrchardsandGroves: ["entre pomares e bosques"],
    detail_AshRichSoil: ["em solo enriquecido pelas cinzas do vulcão"],
    detail_FungalCaverns: ["junto a cavernas onde crescem fungos comestíveis"],
    detail_DatePalms: ["entre bosques de tamareiras"],
    detail_SacredSpring: ["em torno de uma fonte sagrada"],
    detail_StandingStones: ["junto a um círculo de menires antigos"],
    detail_SiteofaMiracle: ["onde se testemunhou um milagre"],
    detail_SaintsTomb: ["em torno do túmulo de um santo"],
    detail_FallenStar: ["onde uma estrela caiu do céu"],
    detail_FireMountain: ["para cultuar o fogo da montanha"],
    detail_BorderKeep: ["em torno de uma fortaleza de fronteira"],
    detail_HilltopFort: ["abaixo de um forte no alto do morro"],
    detail_Watchtower: ["em torno de uma torre de vigia solitária"],
    detail_LegionCamp: ["no lugar de um antigo acampamento de legião"],
    detail_TradeRoads: ["onde duas estradas de comércio se cruzam"],
    detail_CaravanRoute: ["como parada de uma rota de caravanas"],
    detail_PilgrimRoad: ["como pouso numa estrada de peregrinos"],
    detail_RiverJunction: ["onde dois rios se encontram"],
    detail_TunnelJunction: ["onde grandes túneis se cruzam"],
    detail_War: ["por famílias que fugiam de uma guerra"],
    detail_Persecution: ["por gente que fugia de perseguição"],
    detail_Plague: ["por sobreviventes que fugiam de uma peste"],
    detail_NaturalDisaster: ["por sobreviventes de uma grande catástrofe"],
    detail_Monsters: ["por gente expulsa de casa por monstros"],
    detail_GreatHerds: ["para seguir as grandes manadas"],
    detail_DeepWoods: ["à beira de matas fechadas e cheias de caça"],
    detail_FurRichWilds: ["para caçar nas terras selvagens ricas em peles"],
    detail_TeemingWaters: ["junto a águas cheias de peixes"],
    detail_CaveBeasts: ["para caçar as feras das cavernas profundas"],
    detail_ElvenRuins: ["entre ruínas élficas"],
    detail_DwarvenHold: ["numa fortaleza anã abandonada"],
    detail_FallenEmpire: ["entre as ruínas de um império caído"],
    detail_ForgottenTemple: ["em torno de um templo esquecido"],
    detail_GiantsRuin: ["nas ruínas deixadas por gigantes"],
    detail_FreshSpring: ["em torno de uma fonte de água doce"],
    detail_HotSprings: ["em torno de fontes termais fumegantes"],
    detail_DeepWell: ["em torno de um poço profundo"],
    detail_RoyalCharter: ["por carta régia"],
    detail_TempleDecree: ["por decreto de um templo"],
    detail_GuildCharter: ["sob a carta de uma guilda"],
    detail_PenalColony: ["como colônia penal"],

    age_Recent: ["há poucos anos", "ainda dentro da memória dos vivos"],
    age_Generations: ["há algumas gerações", "no tempo dos avós dos mais velhos"],
    age_Centuries: ["há séculos", "há várias centenas de anos"],
    age_Ancient: ["há tanto tempo que ninguém lembra quem foram os fundadores", "numa era mais antiga que qualquer crônica"],
    age_BuiltOverRuins: ["sobre os alicerces de um povoado muito mais antigo", "sobre as ruínas de um assentamento mais velho"],
    age_RuinsReused: ["com as primeiras casas erguidas das pedras caídas", "com pedras tiradas do que veio antes"],

    growth_Planned: ["Foi {traçado|traçada} segundo um plano desde a primeira pedra, e isso ainda se nota.", "Tudo foi medido e demarcado antes de erguerem o primeiro telhado."],
    growth_Gradual: ["Cresceu devagar, um telhado e um campo de cada vez.", "Ninguém {o|a} planejou; simplesmente cresceu, ano após ano."],
    growth_Migration: ["Uma onda repentina de recém-chegados {o|a} fez crescer mais rápido do que qualquer um esperava.", "Encheu-se quase da noite para o dia quando os colonos chegaram aos montes."],
    growth_Occupation: ["Soldados {o|a} ocuparam antes dos colonos, e a guarnição moldou tudo.", "Cresceu em volta de uma força de ocupação que nunca foi embora de vez."],
    growth_Merged: ["Na verdade são várias comunidades antigas que cresceram umas sobre as outras.", "Povoados vizinhos foram se juntando {a ele|a ela}, e as velhas rivalidades sobrevivem."],
    growth_BoomandBust: ["Já prosperou e se esvaziou mais de uma vez, ao sabor da sorte.", "Sua fortuna subiu e despencou várias vezes."],

    change_NewRuler: ["Um novo governante acaba de assumir, e ninguém sabe ainda o que esperar.", "O poder mudou de mãos há pouco, e velhas lealdades estão sendo postas à prova."],
    change_FailedHarvest: ["A última colheita fracassou, e a fome começa a apertar.", "Uma praga arruinou a colheita deste ano, e os estoques estão acabando."],
    change_ReopenedMine: ["Uma mina antiga acaba de ser reaberta, trazendo trabalho e gente nova.", "Os mineiros acharam um veio novo há pouco, e a esperança está voltando."],
    change_ExhaustedMine: ["A mina está praticamente esgotada, e as famílias estão indo embora.", "O último veio bom se esgotou, e o trabalho foi junto."],
    change_DestroyedBridge: ["A ponte que {o|a} ligava ao mundo foi destruída há pouco.", "A ponte desabou não faz muito tempo, cortando a estrada principal."],
    change_Refugees: ["Refugiados vêm chegando aos montes, e tudo está no limite.", "Estranhos fugindo de problemas em outros lugares não param de chegar, e os ânimos estão curtos."],
    change_Discovery: ["Algo estranho foi descoberto nas redondezas, e os boatos se espalham.", "Uma descoberta recente nas redondezas atraiu visitantes curiosos e perigosos."],
    change_Plague: ["Uma doença se espalha de casa em casa.", "Uma febre tomou conta, e os curandeiros não dão conta."],
    change_NewTradeRoute: ["Uma nova rota comercial começou a trazer mercadores.", "Mercadores só recentemente passaram a vir por aqui, com moedas e notícias."],
    change_LostTradeRoute: ["O comércio que passava por aqui foi para outro lugar.", "As caravanas e os mercadores pararam de vir, e o dinheiro foi junto."],
    change_Monsters: ["Monstros têm sido vistos mais perto do que nunca.", "Algo vem matando os animais à noite, e ninguém conseguiu vê-lo direito."],
    change_Schism: ["Os fiéis se dividiram numa disputa amarga de doutrina.", "Uma briga entre os sacerdotes pôs vizinho contra vizinho."],
    change_Fire: ["Um incêndio devastou parte {dele|dela} há pouco.", "Não faz muito tempo, um incêndio deixou parte {dele|dela} em ruínas enegrecidas."],
    change_Flood: ["Uma enchente varreu as partes mais baixas há pouco.", "Uma enchente recente deixou lama, ruína e dívidas para trás."],
    change_Raid: ["Saqueadores atacaram não faz muito tempo, e as cicatrizes ainda são recentes.", "Um ataque recente custou vidas e bens, e todos temem o próximo."],
    change_Disappearances: ["Pessoas vêm desaparecendo sem deixar rastro.", "Várias pessoas sumiram ultimamente, e ninguém quer falar disso."],
    change_Crackdown: ["Os governantes acabam de impor leis novas e duras.", "Uma repressão recente encheu as celas, e há delatores por toda parte."],
    change_Festival: ["Todos estão ocupados com os preparativos de um grande festival.", "Um festival se aproxima, e o lugar está cheio de preparativos e visitantes."],
    change_Windfall: ["Uma fortuna repentina encheu algumas bolsas e despertou muita inveja.", "Uma riqueza inesperada chegou há pouco, e todos querem sua parte."],
    change_Eruption: ["O vulcão despertou há pouco, cobrindo tudo de cinzas.", "Uma erupção recente enterrou campos e casas sob as cinzas."],

    prosperity_Destitute: ["A maior parte de sua gente mal sobrevive de um dia para o outro."],
    prosperity_Poor: ["A maior parte de sua gente se vira com muito pouco."],
    prosperity_Modest: ["Sua gente vive sem luxo, nem rica nem pobre."],
    prosperity_Comfortable: ["Sua gente vive com conforto, e isso se vê nas casas."],
    prosperity_Wealthy: ["Sua gente vive bem, com dinheiro de sobra."],
    prosperity_ExceptionallyRich: ["Sua gente vive num luxo que poucos lugares conseguiriam imaginar."],

    tone_Peaceful: ["A vida aqui é calma, e os vizinhos cuidam uns dos outros.", "Brigas são raras, e as portas quase nunca ficam trancadas."],
    tone_Lively: ["Sempre há barulho, música e fofoca em algum canto.", "Sua gente adora uma festa, uma pechincha e uma boa história."],
    tone_Harsh: ["A vida aqui é dura, e só os fortes resistem.", "Nada vem fácil por aqui, e ninguém espera que venha."],
    tone_Grim: ["Poucos sorriem aqui, e menos ainda têm esperança.", "Um ar de desalento paira sobre tudo."],
    tone_Mysterious: ["Os moradores guardam seus segredos, e os forasteiros se sentem vigiados.", "Costumes estranhos e olhares discretos sugerem coisas não ditas."],
    tone_Decadent: ["Riqueza e vício se misturam abertamente, e tudo tem seu preço.", "Os prazeres são muitos, e os escrúpulos, poucos."],
    tone_Oppressive: ["Quem manda vigia de perto, e as pessoas falam aos sussurros.", "As regras são muitas, os castigos são duros e as queixas são raras."],
  },
};
