import { defineFieldSet, link } from "../info-fields";

export const BUILDING_TYPES = [
  "Residence",
  "Palace",
  "Castle",
  "Tower",
  "Temple",
  "Tavern",
  "Inn",
  "Shop",
  "Workshop",
  "Library",
  "Prison",
  "Monument",
  "Manor",
  "Townhouse",
  "Cottage",
  "Farmhouse",
  "Longhouse",
  "Hall",
  "Guildhall",
  "Town Hall",
  "Courthouse",
  "Barracks",
  "Guardhouse",
  "Gatehouse",
  "Keep",
  "Fortress",
  "Citadel",
  "Watchtower",
  "Lighthouse",
  "Stable",
  "Barn",
  "Granary",
  "Mill",
  "Bakery",
  "Brewery",
  "Smithy",
  "Forge",
  "Foundry",
  "Shipyard",
  "Warehouse",
  "Market Hall",
  "Bank",
  "Counting House",
  "Bathhouse",
  "Hospital",
  "Apothecary",
  "School",
  "Academy",
  "University",
  "Archive",
  "Museum",
  "Theater",
  "Arena",
  "Coliseum",
  "Shrine",
  "Chapel",
  "Cathedral",
  "Monastery",
  "Convent",
  "Abbey",
  "Mausoleum",
  "Crypt",
  "Tomb",
  "Ossuary",
  "Observatory",
  "Alchemy Laboratory",
  "Wizard’s Sanctum",
  "Enchanter’s Workshop",
  "Portal Chamber",
  "Summoning Chamber",
  "Necromancer’s Lair",
  "Adventurers’ Guild",
  "Thieves’ Den",
  "Hunting Lodge",
  "Outpost",
  "Tollhouse",
  "Customs House",
  "Ferry House",
  "Harbor Office",
  "Boathouse",
  "Bridge",
  "Aqueduct",
  "Cistern",
  "Wellhouse",
  "Sewer Entrance",
  "Dungeon",
  "Mine",
  "Quarry",
  "Sawmill",
  "Greenhouse",
  "Aviary",
  "Kennel",
  "Menagerie",
  "Other",
] as const;

const OWNERS = link(["character", "organization"]);

export const BUILDING_INFO = defineFieldSet(
  [
    { key: "construction", label: "Construction" },
    { key: "function", label: "Function" },
    { key: "location", label: "Location" },
    { key: "ownership", label: "Ownership" },
  ],
  [
    // Construction
    {
      key: "architects",
      label: "Architects",
      group: "construction",
      kind: "link",
      link: link(["character", "organization"], true),
      hint: "The characters or organizations that designed or built it.",
    },
    {
      key: "architecturalStyle",
      label: "Architectural Style",
      group: "construction",
      kind: "text",
      hint: "What it looks like: soaring gothic spires, squat dwarven stone, elven living wood?",
    },
    { key: "builtOn", label: "Built On", group: "construction", kind: "text", hint: "When it was built, in your world's calendar." },
    {
      key: "constructionMaterials",
      label: "Construction Materials",
      group: "construction",
      kind: "text",
      hint: "What it's made of. Timber burns, stone endures, and some materials are rarer than gold.",
    },
    {
      key: "sizeAndLayout",
      label: "Size and Layout",
      group: "construction",
      kind: "text",
      hint: "How big it is and how it's arranged: floors, wings, cellars, secret passages?",
    },
    {
      key: "structuralCondition",
      label: "Structural Condition",
      group: "construction",
      kind: "select",
      options: ["Excellent", "Maintained", "Worn", "Dilapidated", "Ruined", "Destroyed"],
      hint: "What shape it's in today, from pristine to a pile of rubble.",
    },
    // Function
    {
      key: "buildingType",
      label: "Building Type",
      group: "function",
      kind: "select",
      options: BUILDING_TYPES,
      hint: "What kind of building this is.",
    },
    { key: "currentUse", label: "Current Use", group: "function", kind: "text", hint: "What it's used for now — which may not be what it was built for." },
    { key: "formerUse", label: "Former Use", group: "function", kind: "text", hint: "What it used to be. Old purposes leave old secrets." },
    {
      key: "publicAccess",
      label: "Public Access",
      group: "function",
      kind: "select",
      options: ["Open", "Restricted", "Invitation Only", "Members Only", "Forbidden"],
      hint: "Who can walk in. Tells the party whether they need a key, a password or a plan.",
    },
    { key: "servicesOffered", label: "Services Offered", group: "function", kind: "text", hint: "What visitors can get here: rooms, healing, training, goods, answers?" },
    // Location
    {
      key: "associatedGeography",
      label: "Associated Geography",
      group: "location",
      kind: "link",
      link: link(["geography"], true),
      hint: "The natural features it stands on, beside or within.",
    },
    {
      key: "connectedBuildings",
      label: "Connected Buildings",
      group: "location",
      kind: "link",
      link: link(["building"], true),
      hint: "Buildings linked to this one by bridges, tunnels or shared walls.",
    },
    {
      key: "parentBuilding",
      label: "Parent Building",
      group: "location",
      kind: "link",
      link: link(["building"]),
      hint: "The larger building or complex this one is part of.",
    },
    { key: "settlement", label: "Settlement", group: "location", kind: "link", link: link(["settlement"]), hint: "The settlement it stands in." },
    { key: "territory", label: "Territory", group: "location", kind: "link", link: link(["territory"]), hint: "The territory it lies in." },
    // Ownership
    { key: "caretaker", label: "Caretaker", group: "ownership", kind: "link", link: OWNERS, hint: "Who looks after it day to day, if not the owner." },
    {
      key: "occupants",
      label: "Occupants",
      group: "ownership",
      kind: "link",
      link: link(["character", "organization"], true),
      hint: "Who lives or works there now.",
    },
    { key: "owner", label: "Owner", group: "ownership", kind: "link", link: OWNERS, hint: "Who it legally belongs to." },
    {
      key: "previousOwners",
      label: "Previous Owners",
      group: "ownership",
      kind: "link",
      link: link(["character", "organization"], true),
      hint: "Who owned it before. Some may want it back.",
    },
  ]
);
