import { PERSON_STATUSES } from "../../politics/hierarchy-config";
import { defineFieldSet, link, type InfoField } from "../info-fields";

/** Character fields. House and Status keep their `people` columns (groupings and authorities query them). */
const GROUPS = [
  { key: "generic", label: "Generic" },
  { key: "appearance", label: "Appearance" },
  { key: "status", label: "Status" },
  { key: "background", label: "Background" },
  { key: "personality", label: "Personality" },
  { key: "relationships", label: "Relationships" },
] as const;

export const ALIGNMENTS = [
  "Lawful Good",
  "Neutral Good",
  "Chaotic Good",
  "Lawful Neutral",
  "True Neutral",
  "Chaotic Neutral",
  "Lawful Evil",
  "Neutral Evil",
  "Chaotic Evil",
] as const;

export const SOCIAL_BACKGROUNDS = [
  "Aberrant Heir",
  "Acolyte",
  "Agent of the Ninth Quill",
  "Archaeologist",
  "Artisan",
  "Bejeweled Conclave Spy",
  "Charlatan",
  "Chondathan Freebooter",
  "Cosmic Dawn Experiment",
  "Covenant of the Grave Recruit",
  "Criminal",
  "Crucible Storm Chaser",
  "Dead Magic Dweller",
  "Dragon Cultist",
  "Emerald Enclave Caretaker",
  "Entertainer",
  "Familiar Trainer",
  "Farmer",
  "Flaming Fist Mercenary",
  "Genie Touched",
  "Guard",
  "Guide",
  "Harper",
  "Haunted One",
  "Hermit",
  "Horizon Weaver Initiate",
  "House Agent",
  "House Cannith Heir",
  "House Deneith Heir",
  "House Ghallanda Heir",
  "House Jorasco Heir",
  "House Kundarak Heir",
  "House Lyrandar Heir",
  "House Medani Heir",
  "House Orien Heir",
  "House Phiarlan Heir",
  "House Sivis Heir",
  "House Tharashk Heir",
  "House Thuranni Heir",
  "House Vadalis Heir",
  "Ice Fisher",
  "Inquisitive",
  "Investigator",
  "Knight of the Gauntlet",
  "Lords’ Alliance Vassal",
  "Merchant",
  "Mist Wanderer",
  "Moonwell Pilgrim",
  "Mulhorandi Tomb Raider",
  "Mythalkeeper",
  "Noble",
  "Phantasmic Circus Trouper",
  "Purple Dragon Squire",
  "Rashemi Wanderer",
  "Sage",
  "Sailor",
  "Scribe",
  "Seer Apprentice",
  "Shadowmasters Exile",
  "Soldier",
  "Spellfire Initiate",
  "Spirit Medium",
  "Ward of the Sheltering Hands",
  "Wayfarer",
  "Zhentarim Mercenary",
] as const;

const FIELDS: InfoField[] = [
  // Generic
  {
    key: "sex",
    label: "Sex",
    group: "generic",
    kind: "text",
    hint: "The character's biological sex, as their species understands it. Useful for lineage, heirs and how others first perceive them.",
  },
  {
    key: "gender",
    label: "Gender",
    group: "generic",
    kind: "text",
    hint: "How society and culture classify this character, and how they see themselves. Different cultures may understand gender in very different ways.",
  },
  {
    key: "house",
    label: "House",
    group: "generic",
    kind: "link",
    link: link(["organization"]),
    column: "houseId",
    hint: "The noble or great house this character belongs to by birth, marriage or adoption. Drives succession and the House grouping.",
  },
  {
    key: "alignment",
    label: "Alignment",
    group: "generic",
    kind: "select",
    options: ALIGNMENTS,
    hint: "Their moral and ethical compass: do they follow order or freedom, good or evil? A quick guide for playing them consistently.",
  },
  {
    key: "nickname",
    label: "Nickname",
    group: "generic",
    kind: "text",
    hint: "What friends, rivals or the common folk call them. A good nickname tells a story on its own.",
  },
  {
    key: "organizations",
    label: "Organizations",
    group: "generic",
    kind: "link",
    link: link(["organization"], true),
    hint: "Guilds, orders, councils or clans this character is a member of. Shows where their loyalties and resources come from.",
  },
  {
    key: "lastSeen",
    label: "Last Seen",
    group: "generic",
    kind: "link",
    link: link(["territory"]),
    hint: "Where this character was last spotted. Handy for tracking where the party can find them next.",
  },
  // Appearance
  { key: "hair", label: "Hair", group: "appearance", kind: "text", hint: "Color, length, style? Braided, shaved, greying at the temples?" },
  { key: "eyes", label: "Eyes", group: "appearance", kind: "text", hint: "Eye color, size, shape? Anything striking, like a scar or a glow?" },
  { key: "height", label: "Height", group: "appearance", kind: "text", hint: "How tall are they? A number, or a comparison like \"towers over most men\"." },
  { key: "weight", label: "Weight", group: "appearance", kind: "text", hint: "How heavy are they? Slight, stocky, a number — whatever reads best at the table." },
  {
    key: "ethnicity",
    label: "Ethnicity",
    group: "appearance",
    kind: "text",
    hint: "The people or bloodline they descend from. Shapes their looks, customs and how strangers treat them.",
  },
  {
    key: "species",
    label: "Species",
    group: "appearance",
    kind: "link",
    link: link(["species"]),
    hint: "Human, elf, dwarf…? Links to the Species article that describes their kind.",
  },
  // Status
  { key: "age", label: "Age", group: "status", kind: "text", hint: "How old are they? Years, or a feel like \"young adult\" or \"ancient\" if it's unknown." },
  { key: "dateOfBirth", label: "Date of Birth", group: "status", kind: "text", hint: "When they were born, in your world's calendar. Anchors them on the timeline." },
  { key: "dateOfDeath", label: "Date of Death", group: "status", kind: "text", hint: "When they died, if they have. Leave empty for the living." },
  {
    key: "status",
    label: "Status",
    group: "status",
    kind: "select",
    options: PERSON_STATUSES,
    column: "status",
    hint: "Are they alive, dead, missing? Drives the Status grouping of the Characters folder.",
  },
  // Background
  {
    key: "birthplace",
    label: "Birthplace",
    group: "background",
    kind: "link",
    link: link(["settlement", "territory", "building"]),
    hint: "The settlement, territory or building where they were born. Roots often explain loyalties and accents.",
  },
  {
    key: "culture",
    label: "Culture",
    group: "background",
    kind: "link",
    link: link(["culture"], true),
    hint: "The cultures they were raised in or adopted. Shapes their customs, values and worldview.",
  },
  { key: "education", label: "Education", group: "background", kind: "text", hint: "Where and how they learned: a temple school, a master's workshop, the streets?" },
  {
    key: "formerOccupations",
    label: "Former Occupations",
    group: "background",
    kind: "text",
    hint: "Jobs they held before. Old skills and old contacts tend to resurface.",
  },
  {
    key: "languages",
    label: "Languages",
    group: "background",
    kind: "link",
    link: link(["language"], true),
    hint: "The languages they speak, read or write. Decides who they can talk to — and eavesdrop on.",
  },
  { key: "occupation", label: "Occupation", group: "background", kind: "text", hint: "What they do for a living right now." },
  {
    key: "residence",
    label: "Residence",
    group: "background",
    kind: "link",
    link: link(["building", "settlement"]),
    hint: "Where they live now: a specific building or a settlement. Tells the party where to knock.",
  },
  {
    key: "socialBackground",
    label: "Social Background",
    group: "background",
    kind: "select",
    options: SOCIAL_BACKGROUNDS,
    hint: "The background they come from, as in the player's handbook. A shortcut to their skills and past.",
  },
  // Personality
  { key: "ambitions", label: "Ambitions", group: "personality", kind: "text", hint: "What they want most. Ambitions are what push a character into the story." },
  { key: "fears", label: "Fears", group: "personality", kind: "text", hint: "What they dread or avoid. Fears make great pressure points in a scene." },
  { key: "flaws", label: "Flaws", group: "personality", kind: "text", hint: "A vice, weakness or blind spot others could exploit." },
  { key: "ideals", label: "Ideals", group: "personality", kind: "text", hint: "The principles they believe in and would fight for." },
  { key: "reputation", label: "Reputation", group: "personality", kind: "text", hint: "What people say about them, true or not. It arrives before they do." },
  // Relationships
  {
    key: "allies",
    label: "Allies",
    group: "relationships",
    kind: "link",
    link: link(["character", "organization"], true),
    hint: "Characters and organizations they can count on when things go wrong.",
  },
  { key: "children", label: "Children", group: "relationships", kind: "link", link: link(["character"], true), hint: "Their sons and daughters, by blood or adoption." },
  {
    key: "deities",
    label: "Deities",
    group: "relationships",
    kind: "link",
    link: link(["character", "religion", "generic"], true),
    hint: "The gods, patrons or higher powers they worship or serve.",
  },
  {
    key: "enemies",
    label: "Enemies",
    group: "relationships",
    kind: "link",
    link: link(["character", "organization"], true),
    hint: "Characters and organizations that want them gone. Rivalries drive conflict.",
  },
  { key: "mentors", label: "Mentors", group: "relationships", kind: "link", link: link(["character"], true), hint: "Who taught them what they know." },
  { key: "parents", label: "Parents", group: "relationships", kind: "link", link: link(["character"], true), hint: "Their mother, father or guardians." },
  { key: "partners", label: "Partners", group: "relationships", kind: "link", link: link(["character"], true), hint: "Spouses, lovers or sworn companions." },
  { key: "religion", label: "Religion", group: "relationships", kind: "link", link: link(["religion"], true), hint: "The faiths they follow or were raised in." },
  { key: "siblings", label: "Siblings", group: "relationships", kind: "link", link: link(["character"], true), hint: "Their brothers and sisters — allies, rivals or both." },
  { key: "titles", label: "Titles", group: "relationships", kind: "link", link: link(["title"], true), hint: "Titles they hold or have held, like knighthoods or offices." },
];

export const CHARACTER_INFO = defineFieldSet(GROUPS, FIELDS);
