import { defineFieldSet, link } from "../info-fields";

const CONFLICTS = () => link(["conflict"], true);

export const CONFLICT_INFO = defineFieldSet(
  [
    { key: "causes", label: "Causes" },
    { key: "course", label: "Course of the Conflict" },
    { key: "identity", label: "Identity" },
    { key: "locations", label: "Locations" },
    { key: "participants", label: "Participants" },
    { key: "resourcesAndMethods", label: "Resources and Methods" },
    { key: "resolution", label: "Resolution and Consequences" },
    { key: "timeline", label: "Timeline" },
    { key: "worldbuilding", label: "Worldbuilding" },
  ],
  [
    // Causes
    { key: "competingClaims", label: "Competing Claims", group: "causes", kind: "text", hint: "What each side claims is rightfully theirs." },
    { key: "immediateTrigger", label: "Immediate Trigger", group: "causes", kind: "text", hint: "The spark that set it off." },
    { key: "objectivesOfEachSide", label: "Objectives of Each Side", group: "causes", kind: "text", hint: "What each side wants to walk away with." },
    { key: "rootCauses", label: "Root Causes", group: "causes", kind: "text", hint: "The deep reasons behind it." },
    {
      key: "underlyingTensions",
      label: "Underlying Tensions",
      group: "causes",
      kind: "link",
      link: link(["culture", "religion", "law", "organization"], true),
      hint: "Cultures, faiths, laws or organizations at the heart of the tension.",
    },
    {
      key: "violatedAgreements",
      label: "Violated Agreements",
      group: "causes",
      kind: "link",
      link: link(["document", "law"], true),
      hint: "Treaties or laws that were broken.",
    },
    // Course of the Conflict
    { key: "escalation", label: "Escalation", group: "course", kind: "text", hint: "How it grew from its first spark." },
    { key: "interventions", label: "Interventions", group: "course", kind: "text", hint: "Outside powers that stepped in, and how." },
    {
      key: "majorEvents",
      label: "Major Events",
      group: "course",
      kind: "link",
      link: link(["conflict", "generic"], true),
      hint: "Battles and events within it.",
    },
    { key: "negotiations", label: "Negotiations", group: "course", kind: "text", hint: "Attempts to talk it out, and how they went." },
    { key: "turningPoints", label: "Turning Points", group: "course", kind: "text", hint: "The moments that changed its direction." },
    { key: "unexpectedDevelopments", label: "Unexpected Developments", group: "course", kind: "text", hint: "Twists nobody saw coming." },
    // Identity
    {
      key: "conflictType",
      label: "Conflict Type",
      group: "identity",
      kind: "select",
      multiple: true,
      options: [
        "War",
        "Battle",
        "Siege",
        "Skirmish",
        "Invasion",
        "Civil War",
        "Rebellion",
        "Revolution",
        "Coup",
        "Succession Dispute",
        "Political Rivalry",
        "Religious Schism",
        "Trade Dispute",
        "Territorial Dispute",
        "Feud",
        "Other",
      ],
      hint: "What kind of conflict this is. Pick every kind that applies.",
    },
    { key: "parentConflict", label: "Parent Conflict", group: "identity", kind: "link", link: link(["conflict"]), hint: "The larger conflict this one is part of." },
    {
      key: "publicAwareness",
      label: "Public Awareness",
      group: "identity",
      kind: "select",
      options: ["Public", "Partially Known", "Secret", "Forgotten", "Disputed"],
      hint: "How much the world knows about it.",
    },
    { key: "relatedConflicts", label: "Related Conflicts", group: "identity", kind: "link", link: CONFLICTS(), hint: "Conflicts connected to this one." },
    {
      key: "scale",
      label: "Scale",
      group: "identity",
      kind: "select",
      options: ["Personal", "Local", "Regional", "National", "Continental", "Worldwide", "Planar", "Multiplanar"],
      hint: "How far it reaches.",
    },
    {
      key: "status",
      label: "Status",
      group: "identity",
      kind: "select",
      options: ["Brewing", "Ongoing", "Paused", "Resolved", "Abandoned", "Unknown"],
      hint: "Where it stands today.",
    },
    // Locations
    {
      key: "affectedSettlements",
      label: "Affected Settlements",
      group: "locations",
      kind: "link",
      link: link(["settlement"], true),
      hint: "Settlements touched by it.",
    },
    {
      key: "affectedTerritories",
      label: "Affected Territories",
      group: "locations",
      kind: "link",
      link: link(["territory"], true),
      hint: "Territories touched by it.",
    },
    {
      key: "primaryLocation",
      label: "Primary Location",
      group: "locations",
      kind: "link",
      link: link(["geography", "territory", "settlement", "building"]),
      hint: "Where most of it happens.",
    },
    {
      key: "strategicLocations",
      label: "Strategic Locations",
      group: "locations",
      kind: "link",
      link: link(["building", "settlement", "geography"], true),
      hint: "Places both sides fight to hold.",
    },
    // Participants
    {
      key: "affectedCommunities",
      label: "Affected Communities",
      group: "participants",
      kind: "link",
      link: link(["settlement", "culture", "organization"], true),
      hint: "Communities caught up in it.",
    },
    {
      key: "commandersAndLeaders",
      label: "Commanders and Leaders",
      group: "participants",
      kind: "link",
      link: link(["character"], true),
      hint: "The characters leading each side.",
    },
    {
      key: "externalSupporters",
      label: "External Supporters",
      group: "participants",
      kind: "link",
      link: link(["character", "organization", "territory"], true),
      hint: "Outsiders backing a side with gold, arms or words.",
    },
    {
      key: "mediators",
      label: "Mediators",
      group: "participants",
      kind: "link",
      link: link(["character", "organization"], true),
      hint: "Those trying to broker peace.",
    },
    { key: "militaryForces", label: "Military Forces", group: "participants", kind: "link", link: link(["military"], true), hint: "Forces fighting in it." },
    {
      key: "participatingOrganizations",
      label: "Participating Organizations",
      group: "participants",
      kind: "link",
      link: link(["organization"], true),
      hint: "Organizations taking part.",
    },
    {
      key: "participatingTerritories",
      label: "Participating Territories",
      group: "participants",
      kind: "link",
      link: link(["territory"], true),
      hint: "Territories taking part.",
    },
    { key: "sidesAndAllegiances", label: "Sides and Allegiances", group: "participants", kind: "text", hint: "Who stands with whom." },
    // Resources and Methods
    { key: "balanceOfPower", label: "Balance of Power", group: "resourcesAndMethods", kind: "text", hint: "Which side holds the advantage, and why." },
    { key: "fundingAndSupplies", label: "Funding and Supplies", group: "resourcesAndMethods", kind: "text", hint: "How each side pays for and feeds its fight." },
    {
      key: "intelligenceAndEspionage",
      label: "Intelligence and Espionage",
      group: "resourcesAndMethods",
      kind: "text",
      hint: "Spies, scouts and secrets in play.",
    },
    { key: "magicUsed", label: "Magic Used", group: "resourcesAndMethods", kind: "link", link: link(["magic"], true), hint: "Magic brought to bear." },
    {
      key: "notableEquipment",
      label: "Notable Equipment",
      group: "resourcesAndMethods",
      kind: "link",
      link: link(["item"], true),
      hint: "Items that made a difference.",
    },
    {
      key: "technologiesUsed",
      label: "Technologies Used",
      group: "resourcesAndMethods",
      kind: "link",
      link: link(["technology"], true),
      hint: "Technologies used in the fighting.",
    },
    {
      key: "unconventionalMethods",
      label: "Unconventional Methods",
      group: "resourcesAndMethods",
      kind: "text",
      hint: "Tricks, sabotage or tactics nobody expected.",
    },
    // Resolution and Consequences
    { key: "casualtiesAndLosses", label: "Casualties and Losses", group: "resolution", kind: "text", hint: "What it cost in lives and property." },
    { key: "displacedPopulations", label: "Displaced Populations", group: "resolution", kind: "text", hint: "Who was driven from their homes." },
    { key: "economicEffects", label: "Economic Effects", group: "resolution", kind: "text", hint: "What it did to trade, prices and fortunes." },
    { key: "outcome", label: "Outcome", group: "resolution", kind: "text", hint: "How it ended — or where it stands." },
    { key: "politicalChanges", label: "Political Changes", group: "resolution", kind: "text", hint: "How power shifted afterwards." },
    {
      key: "resolutionMethod",
      label: "Resolution Method",
      group: "resolution",
      kind: "select",
      options: [
        "Military Victory",
        "Negotiated Settlement",
        "Arbitration",
        "Surrender",
        "Withdrawal",
        "Reconciliation",
        "Mutual Exhaustion",
        "External Intervention",
        "Other",
      ],
      hint: "How it came to an end.",
    },
    { key: "resultingLaws", label: "Resulting Laws", group: "resolution", kind: "link", link: link(["law"], true), hint: "Laws born from it." },
    {
      key: "settlementAgreements",
      label: "Settlement Agreements",
      group: "resolution",
      kind: "link",
      link: link(["document"], true),
      hint: "Treaties and accords that ended it.",
    },
    { key: "territorialChanges", label: "Territorial Changes", group: "resolution", kind: "text", hint: "Lands that changed hands." },
    { key: "unresolvedIssues", label: "Unresolved Issues", group: "resolution", kind: "text", hint: "What was left unsettled — the seeds of the next conflict." },
    // Timeline
    { key: "beganOn", label: "Began On", group: "timeline", kind: "text", hint: "When it started." },
    { key: "endedOn", label: "Ended On", group: "timeline", kind: "text", hint: "When it ended, if it has." },
    { key: "periodsOfTruce", label: "Periods of Truce", group: "timeline", kind: "text", hint: "Pauses in the fighting." },
    { key: "precedingConflicts", label: "Preceding Conflicts", group: "timeline", kind: "link", link: CONFLICTS(), hint: "Conflicts that led to this one." },
    { key: "subsequentConflicts", label: "Subsequent Conflicts", group: "timeline", kind: "link", link: CONFLICTS(), hint: "Conflicts that followed from it." },
    // Worldbuilding
    {
      key: "commemorations",
      label: "Commemorations",
      group: "worldbuilding",
      kind: "link",
      link: link(["tradition"], true),
      hint: "Traditions that remember it.",
    },
    {
      key: "conflictingAccounts",
      label: "Conflicting Accounts",
      group: "worldbuilding",
      kind: "link",
      link: link(["document"], true),
      hint: "Documents that tell the story differently.",
    },
    { key: "culturalMemory", label: "Cultural Memory", group: "worldbuilding", kind: "text", hint: "How people remember it today." },
    {
      key: "historicalEvidence",
      label: "Historical Evidence",
      group: "worldbuilding",
      kind: "link",
      link: link(["document", "item", "building"], true),
      hint: "What's left that proves it happened.",
    },
    { key: "lastingGrievances", label: "Lasting Grievances", group: "worldbuilding", kind: "text", hint: "Wounds that never healed." },
    { key: "memorials", label: "Memorials", group: "worldbuilding", kind: "link", link: link(["building", "geography"], true), hint: "Monuments and sites honoring it." },
    { key: "unansweredQuestions", label: "Unanswered Questions", group: "worldbuilding", kind: "text", hint: "Mysteries it left behind — great hooks for a campaign." },
  ]
);
