import { defineFieldSet, link } from "../info-fields";

export const GEOGRAPHY_INFO = defineFieldSet(
  [
    { key: "environment", label: "Environment" },
    { key: "features", label: "Features" },
    { key: "historyAndAssociations", label: "History and Associations" },
    { key: "location", label: "Location" },
  ],
  [
    // Environment
    {
      key: "climate",
      label: "Climate",
      group: "environment",
      kind: "select",
      options: [
        "Polar",
        "Subpolar",
        "Temperate",
        "Subtropical",
        "Tropical",
        "Supernatural",
        "Arid",
        "Semi-Arid",
        "Mediterranean",
        "Oceanic",
        "Continental",
        "Highland",
        "Alpine",
        "Equatorial",
        "Volcanic",
      ],
      hint: "The usual weather over the year. Decides what travelers need to pack.",
    },
    { key: "commonWildlife", label: "Common Wildlife", group: "environment", kind: "text", hint: "The animals and monsters most often seen there." },
    {
      key: "environmentalHazards",
      label: "Environmental Hazards",
      group: "environment",
      kind: "text",
      hint: "What can kill the unwary: quicksand, avalanches, poison mists, wild magic?",
    },
    {
      key: "notableSpecies",
      label: "Notable Species",
      group: "environment",
      kind: "link",
      link: link(["species"], true),
      hint: "Species that live there or are known from there.",
    },
    {
      key: "primaryBiome",
      label: "Primary Biome",
      group: "environment",
      kind: "select",
      options: [
        "Forest",
        "Grassland",
        "Desert",
        "Tundra",
        "Wetland",
        "Jungle",
        "Alpine",
        "Aquatic",
        "Savanna",
        "Steppe",
        "Shrubland",
        "Heathland",
        "Taiga",
        "Cloud Forest",
        "Mangrove",
        "Swamp",
        "Bog",
        "Coastal",
        "Coral Reef",
        "Kelp Forest",
        "Riverine",
        "Glacier",
        "Ice Sheet",
        "Badlands",
        "Salt Flat",
        "Volcanic Wasteland",
        "Subterranean",
        "Fungal",
        "Blighted",
        "Enchanted",
        "Other",
      ],
      hint: "The main kind of landscape and ecosystem found there.",
    },
    { key: "seasonalChanges", label: "Seasonal Changes", group: "environment", kind: "text", hint: "How it changes through the year: floods, frozen rivers, migrations?" },
    // Features
    {
      key: "elevationOrDepth",
      label: "Elevation or Depth",
      group: "features",
      kind: "text",
      hint: "How high it rises or how deep it goes.",
    },
    {
      key: "featureType",
      label: "Feature Type",
      group: "features",
      kind: "select",
      options: ["Continent", "Island", "Archipelago", "Mountain", "Mountain Range", "Valley", "Forest", "Desert", "River", "Lake", "Sea", "Cave", "Other"],
      hint: "What kind of geographic feature this is.",
    },
    {
      key: "naturalResources",
      label: "Natural Resources",
      group: "features",
      kind: "text",
      hint: "Timber, ore, game, herbs, gems? Resources are what people fight over.",
    },
    { key: "sizeOrExtent", label: "Size or Extent", group: "features", kind: "text", hint: "How large it is, or how far it stretches." },
    {
      key: "unusualProperties",
      label: "Unusual Properties",
      group: "features",
      kind: "text",
      hint: "Anything strange about it: floating rocks, time slipping, whispering trees?",
    },
    // History and Associations
    {
      key: "associatedCultures",
      label: "Associated Cultures",
      group: "historyAndAssociations",
      kind: "link",
      link: link(["culture"], true),
      hint: "Cultures that live there, hold it sacred or come from it.",
    },
    {
      key: "historicalEvents",
      label: "Historical Events",
      group: "historyAndAssociations",
      kind: "link",
      link: link(["generic"], true),
      hint: "Battles, disasters and other events that happened there.",
    },
    { key: "legends", label: "Legends", group: "historyAndAssociations", kind: "text", hint: "Tales told about the place, true or not." },
    {
      key: "religiousSignificance",
      label: "Religious Significance",
      group: "historyAndAssociations",
      kind: "link",
      link: link(["religion"], true),
      hint: "Faiths that consider it holy, cursed or important.",
    },
    {
      key: "ruinsAndStructures",
      label: "Ruins and Structures",
      group: "historyAndAssociations",
      kind: "link",
      link: link(["building"], true),
      hint: "Buildings and ruins found there. Perfect dungeon material.",
    },
    // Location
    {
      key: "adjacentFeatures",
      label: "Adjacent Features",
      group: "location",
      kind: "link",
      link: link(["geography"], true),
      hint: "Natural features that border this one.",
    },
    {
      key: "containedFeatures",
      label: "Contained Features",
      group: "location",
      kind: "link",
      link: link(["geography"], true),
      hint: "Smaller features inside this one, like peaks in a range or islands in a sea.",
    },
    {
      key: "nearbySettlements",
      label: "Nearby Settlements",
      group: "location",
      kind: "link",
      link: link(["settlement"], true),
      hint: "Settlements within reach. Where travelers can rest or resupply.",
    },
    {
      key: "overlappingTerritories",
      label: "Overlapping Territories",
      group: "location",
      kind: "link",
      link: link(["territory"], true),
      hint: "Territories it lies in or crosses.",
    },
    {
      key: "parentGeographicFeature",
      label: "Parent Geographic Feature",
      group: "location",
      kind: "link",
      link: link(["geography"]),
      hint: "The larger feature this one is part of.",
    },
  ]
);
