import { defineFieldSet, link } from "../info-fields";

const LANGUAGES = () => link(["language"], true);

export const LANGUAGE_INFO = defineFieldSet(
  [
    { key: "history", label: "History" },
    { key: "identity", label: "Identity" },
    { key: "relationships", label: "Relationships" },
    { key: "usage", label: "Usage" },
    { key: "writing", label: "Writing" },
    { key: "worldbuilding", label: "Worldbuilding" },
  ],
  [
    // History
    { key: "dateOfOrigin", label: "Date of Origin", group: "history", kind: "text", hint: "When the language first appeared." },
    {
      key: "developedBy",
      label: "Developed By",
      group: "history",
      kind: "link",
      link: link(["character", "organization", "culture"], true),
      hint: "Who shaped or invented it.",
    },
    {
      key: "placeOfOrigin",
      label: "Place of Origin",
      group: "history",
      kind: "link",
      link: link(["territory", "settlement", "geography"], true),
      hint: "Where it was first spoken.",
    },
    {
      key: "status",
      label: "Status",
      group: "history",
      kind: "select",
      options: ["Widely Used", "Declining", "Endangered", "Dormant", "Extinct", "Revived", "Unknown"],
      hint: "How alive the language is today.",
    },
    // Identity
    { key: "endonym", label: "Endonym", group: "identity", kind: "text", hint: "What its speakers call the language in the language itself." },
    {
      key: "languageFamily",
      label: "Language Family",
      group: "identity",
      kind: "link",
      link: link(["generic"]),
      hint: "The family of related languages it belongs to.",
    },
    {
      key: "originType",
      label: "Origin Type",
      group: "identity",
      kind: "select",
      options: ["Naturally Developed", "Deliberately Constructed", "Divine", "Supernatural", "Unknown"],
      hint: "How it came to be: grown over centuries, invented, given by gods?",
    },
    {
      key: "varietyType",
      label: "Variety Type",
      group: "identity",
      kind: "select",
      options: ["Language", "Dialect", "Pidgin", "Creole", "Other"],
      hint: "Whether this is a full language or a variety of one.",
    },
    // Relationships
    { key: "derivedLanguages", label: "Derived Languages", group: "relationships", kind: "link", link: LANGUAGES(), hint: "Languages that grew out of this one." },
    { key: "dialects", label: "Dialects", group: "relationships", kind: "link", link: LANGUAGES(), hint: "Regional or social varieties of it." },
    { key: "influencedBy", label: "Influenced By", group: "relationships", kind: "link", link: LANGUAGES(), hint: "Languages it borrowed words or grammar from." },
    {
      key: "mutuallyIntelligibleLanguages",
      label: "Mutually Intelligible Languages",
      group: "relationships",
      kind: "link",
      link: LANGUAGES(),
      hint: "Languages whose speakers can more or less understand each other.",
    },
    { key: "parentLanguage", label: "Parent Language", group: "relationships", kind: "link", link: link(["language"]), hint: "The language it descends from." },
    // Usage
    { key: "associatedCultures", label: "Associated Cultures", group: "usage", kind: "link", link: link(["culture"], true), hint: "Cultures that speak it." },
    { key: "associatedReligions", label: "Associated Religions", group: "usage", kind: "link", link: link(["religion"], true), hint: "Faiths that use it in worship or scripture." },
    {
      key: "communicationModes",
      label: "Communication Modes",
      group: "usage",
      kind: "select",
      multiple: true,
      options: ["Spoken", "Signed", "Written", "Tactile", "Whistled", "Telepathic", "Other"],
      hint: "How it's communicated. Pick every mode that applies.",
    },
    { key: "notableSpeakers", label: "Notable Speakers", group: "usage", kind: "link", link: link(["character"], true), hint: "Characters known for speaking it." },
    { key: "numberOfUsers", label: "Number of Users", group: "usage", kind: "text", hint: "Roughly how many speak it." },
    {
      key: "officialRecognition",
      label: "Official Recognition",
      group: "usage",
      kind: "link",
      link: link(["territory", "organization"], true),
      hint: "Territories or organizations that make it official.",
    },
    {
      key: "primaryRole",
      label: "Primary Role",
      group: "usage",
      kind: "select",
      options: ["Everyday Communication", "Trade", "Diplomacy", "Religion", "Scholarship", "Ceremonies", "Secret Communication", "Magic", "Other"],
      hint: "What it's mainly used for.",
    },
    {
      key: "regionsUsed",
      label: "Regions Used",
      group: "usage",
      kind: "link",
      link: link(["territory", "settlement", "geography"], true),
      hint: "Where it's spoken today.",
    },
    {
      key: "usingOrganizations",
      label: "Using Organizations",
      group: "usage",
      kind: "link",
      link: link(["organization"], true),
      hint: "Guilds, orders or cabals that use it.",
    },
    // Writing
    { key: "alphabetOrSymbols", label: "Alphabet or Symbols", group: "writing", kind: "text", hint: "What its writing looks like: letters, runes, glyphs, knots?" },
    { key: "notableTexts", label: "Notable Texts", group: "writing", kind: "link", link: link(["document"], true), hint: "Important documents written in it." },
    { key: "scriptNames", label: "Script Names", group: "writing", kind: "text", hint: "The names of the scripts used to write it." },
    {
      key: "writingDirection",
      label: "Writing Direction",
      group: "writing",
      kind: "select",
      options: ["Left to Right", "Right to Left", "Vertical", "Alternating", "Variable", "Other"],
      hint: "Which way it's written.",
    },
    // Worldbuilding
    {
      key: "associatedMagic",
      label: "Associated Magic",
      group: "worldbuilding",
      kind: "link",
      link: link(["generic", "religion", "item"], true),
      hint: "Magic tied to the language: spells, faiths, enchanted items.",
    },
    { key: "culturalSignificance", label: "Cultural Significance", group: "worldbuilding", kind: "text", hint: "What the language means to its speakers." },
    { key: "learningRequirements", label: "Learning Requirements", group: "worldbuilding", kind: "text", hint: "What it takes to learn it: a teacher, a pact, years of study?" },
    {
      key: "restrictionsOnUse",
      label: "Restrictions on Use",
      group: "worldbuilding",
      kind: "link",
      link: link(["law"], true),
      hint: "Laws that limit or forbid speaking it.",
    },
    {
      key: "supernaturalProperties",
      label: "Supernatural Properties",
      group: "worldbuilding",
      kind: "text",
      hint: "Anything uncanny about it: words that burn, names with power?",
    },
    { key: "tabooWords", label: "Taboo Words", group: "worldbuilding", kind: "text", hint: "Words never to be spoken, and what happens if they are." },
  ]
);
