import { defineFieldSet, link } from "../info-fields";

const MAGIC_SOURCES = [
  "Arcane",
  "Divine",
  "Primal",
  "Psionic",
  "Innate",
  "Pact-Granted",
  "Alchemical",
  "Elemental",
  "Fey",
  "Fiendish",
  "Celestial",
  "Draconic",
  "Ancestral",
  "Spirit",
  "Cosmic",
  "Astral",
  "Shadow",
  "Dream",
  "Blood",
  "Runic",
  "Leyline",
  "Artifact",
  "Wild Magic",
  "Primordial",
  "Planar",
  "Other",
];

/** Magic & Spells: spells, rituals, schools, traditions and systems of magic. */
export const MAGIC_INFO = defineFieldSet(
  [
    { key: "casting", label: "Casting" },
    { key: "classification", label: "Classification" },
    { key: "effects", label: "Effects" },
    { key: "historyAndTeaching", label: "History and Teaching" },
    { key: "limitations", label: "Limitations" },
    { key: "relationships", label: "Relationships" },
    { key: "society", label: "Society" },
  ],
  [
    // Casting
    {
      key: "castingMethod",
      label: "Casting Method",
      group: "casting",
      kind: "select",
      options: ["Incantation", "Gesture", "Inscription", "Meditation", "Performance", "Prayer", "Alchemy", "Innate Will", "Combined", "Other"],
      hint: "How it's cast.",
    },
    { key: "castingTime", label: "Casting Time", group: "casting", kind: "text", hint: "How long it takes to cast: an action, a minute, a night of chanting?" },
    {
      key: "components",
      label: "Components",
      group: "casting",
      kind: "select",
      multiple: true,
      options: ["Verbal", "Somatic", "Material", "Focus", "Mental", "Other"],
      hint: "What casting it requires. Pick every component that applies.",
    },
    { key: "focusItems", label: "Focus Items", group: "casting", kind: "text", hint: "Wands, holy symbols or other foci it's channeled through." },
    { key: "materialComponents", label: "Material Components", group: "casting", kind: "text", hint: "The materials used in casting it." },
    { key: "materialRequirements", label: "Material Requirements", group: "casting", kind: "text", hint: "Costly or consumed materials, and how much of them." },
    { key: "numberOfParticipants", label: "Number of Participants", group: "casting", kind: "text", hint: "How many casters it takes." },
    {
      key: "requiredConditions",
      label: "Required Conditions",
      group: "casting",
      kind: "text",
      hint: "Conditions that must be met: a place, a time, a phase of the moon?",
    },
    { key: "ritualProcedure", label: "Ritual Procedure", group: "casting", kind: "text", hint: "The steps of the ritual, in order." },
    // Classification
    {
      key: "articleScope",
      label: "Article Scope",
      group: "classification",
      kind: "select",
      options: ["Spell", "Ritual", "Magical Technique", "School of Magic", "Magical Tradition", "Magic System", "Supernatural Phenomenon", "Other"],
      hint: "Is this article about a single spell, a ritual, a school, or a whole system of magic?",
    },
    {
      key: "magicSource",
      label: "Magic Source",
      group: "classification",
      kind: "select",
      options: MAGIC_SOURCES,
      hint: "Where the power comes from.",
    },
    {
      key: "school",
      label: "School",
      group: "classification",
      kind: "select",
      options: ["Abjuration", "Conjuration", "Divination", "Enchantment", "Evocation", "Illusion", "Necromancy", "Transmutation", "Other"],
      hint: "Its school of magic.",
    },
    {
      key: "spellLevelOrRank",
      label: "Spell Level or Rank",
      group: "classification",
      kind: "select",
      options: ["Cantrip", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
      hint: "How powerful it is.",
    },
    {
      key: "status",
      label: "Status",
      group: "classification",
      kind: "select",
      options: ["Practiced", "Experimental", "Obsolete", "Lost", "Rediscovered", "Disputed"],
      hint: "Whether anyone still knows it.",
    },
    // Effects
    { key: "areaOfEffect", label: "Area of Effect", group: "effects", kind: "text", hint: "The area it covers." },
    { key: "duration", label: "Duration", group: "effects", kind: "text", hint: "How long its effect lasts." },
    { key: "observableSigns", label: "Observable Signs", group: "effects", kind: "text", hint: "What onlookers see, hear or smell when it's cast." },
    { key: "primaryEffect", label: "Primary Effect", group: "effects", kind: "text", hint: "What it does." },
    { key: "range", label: "Range", group: "effects", kind: "text", hint: "How far it reaches." },
    { key: "secondaryEffects", label: "Secondary Effects", group: "effects", kind: "text", hint: "Lesser effects that come with it." },
    { key: "targetRequirements", label: "Target Requirements", group: "effects", kind: "text", hint: "What a target must be for it to work." },
    { key: "targets", label: "Targets", group: "effects", kind: "text", hint: "Who or what it can affect." },
    // History and Teaching
    { key: "dateOfDiscovery", label: "Date of Discovery", group: "historyAndTeaching", kind: "text", hint: "When it was first discovered or created." },
    {
      key: "discoverersOrCreators",
      label: "Discoverers or Creators",
      group: "historyAndTeaching",
      kind: "link",
      link: link(["character", "organization"], true),
      hint: "Who found or created it.",
    },
    {
      key: "learningRequirements",
      label: "Learning Requirements",
      group: "historyAndTeaching",
      kind: "text",
      hint: "What it takes to learn it: study, a pact, a bloodline?",
    },
    {
      key: "notablePractitioners",
      label: "Notable Practitioners",
      group: "historyAndTeaching",
      kind: "link",
      link: link(["character"], true),
      hint: "Characters known for using it.",
    },
    {
      key: "placeOfOrigin",
      label: "Place of Origin",
      group: "historyAndTeaching",
      kind: "link",
      link: link(["building", "settlement", "geography"], true),
      hint: "Where it was first cast.",
    },
    {
      key: "teachingOrganizations",
      label: "Teaching Organizations",
      group: "historyAndTeaching",
      kind: "link",
      link: link(["organization"], true),
      hint: "Academies, orders or covens that teach it.",
    },
    {
      key: "teachingTexts",
      label: "Teaching Texts",
      group: "historyAndTeaching",
      kind: "link",
      link: link(["document"], true),
      hint: "Spellbooks, grimoires and scrolls that record it.",
    },
    // Limitations
    {
      key: "concentration",
      label: "Concentration",
      group: "limitations",
      kind: "select",
      options: ["Required", "Not Required", "Conditional"],
      hint: "Whether the caster must keep focus to sustain it.",
    },
    { key: "costsAndSacrifices", label: "Costs and Sacrifices", group: "limitations", kind: "text", hint: "What the caster gives up to cast it." },
    { key: "countersAndDefenses", label: "Counters and Defenses", group: "limitations", kind: "text", hint: "How it can be blocked, dispelled or resisted." },
    { key: "failureConsequences", label: "Failure Consequences", group: "limitations", kind: "text", hint: "What happens when casting goes wrong." },
    { key: "recoveryOrRecharge", label: "Recovery or Recharge", group: "limitations", kind: "text", hint: "How soon it can be cast again." },
    {
      key: "resistanceOrSavingThrow",
      label: "Resistance or Saving Throw",
      group: "limitations",
      kind: "text",
      hint: "How a target can resist it.",
    },
    { key: "sideEffects", label: "Side Effects", group: "limitations", kind: "text", hint: "Unwanted effects on the caster or the world around." },
    { key: "usageLimits", label: "Usage Limits", group: "limitations", kind: "text", hint: "How often it can be used." },
    // Relationships
    {
      key: "associatedDeitiesOrPatrons",
      label: "Associated Deities or Patrons",
      group: "relationships",
      kind: "link",
      link: link(["character", "religion", "generic"], true),
      hint: "The gods or patrons who grant or favor it.",
    },
    { key: "associatedItems", label: "Associated Items", group: "relationships", kind: "link", link: link(["item"], true), hint: "Items linked to it." },
    {
      key: "associatedLocations",
      label: "Associated Locations",
      group: "relationships",
      kind: "link",
      link: link(["building", "geography"], true),
      hint: "Places tied to it.",
    },
    {
      key: "prerequisiteMagic",
      label: "Prerequisite Magic",
      group: "relationships",
      kind: "link",
      link: link(["magic"], true),
      hint: "Magic that must be mastered first.",
    },
    { key: "relatedSpells", label: "Related Spells", group: "relationships", kind: "link", link: link(["magic"], true), hint: "Spells similar to this one." },
    { key: "variants", label: "Variants", group: "relationships", kind: "link", link: link(["magic"], true), hint: "Altered versions of it." },
    // Society
    {
      key: "associatedTraditions",
      label: "Associated Traditions",
      group: "society",
      kind: "link",
      link: link(["tradition"], true),
      hint: "Traditions where it's used.",
    },
    { key: "culturalSignificance", label: "Cultural Significance", group: "society", kind: "text", hint: "What it means to the people who use it." },
    { key: "legalRestrictions", label: "Legal Restrictions", group: "society", kind: "link", link: link(["law"], true), hint: "Laws that limit or ban it." },
    {
      key: "publicPerception",
      label: "Public Perception",
      group: "society",
      kind: "select",
      options: ["Celebrated", "Accepted", "Tolerated", "Distrusted", "Feared", "Hated", "Unknown"],
      hint: "How ordinary people see it — and those who cast it.",
    },
    {
      key: "regulatingOrganizations",
      label: "Regulating Organizations",
      group: "society",
      kind: "link",
      link: link(["organization"], true),
      hint: "Organizations that control or police it.",
    },
    {
      key: "secrecy",
      label: "Secrecy",
      group: "society",
      kind: "select",
      options: ["Common Knowledge", "Specialist Knowledge", "Restricted", "Secret", "Forgotten"],
      hint: "How widely known it is.",
    },
  ]
);
