import { defineFieldSet, link } from "../info-fields";

const ARMORS = [
  "Padded Armor",
  "Leather Armor",
  "Studded Leather Armor",
  "Hide Armor",
  "Chain Shirt",
  "Scale Mail",
  "Breastplate",
  "Half Plate Armor",
  "Ring Mail",
  "Chain Mail",
  "Splint Armor",
  "Plate Armor",
  "Shield",
];

const WEAPONS = [
  "Club",
  "Dagger",
  "Greatclub",
  "Handaxe",
  "Javelin",
  "Light Hammer",
  "Mace",
  "Quarterstaff",
  "Sickle",
  "Spear",
  "Dart",
  "Light Crossbow",
  "Shortbow",
  "Sling",
  "Battleaxe",
  "Flail",
  "Glaive",
  "Greataxe",
  "Greatsword",
  "Halberd",
  "Lance",
  "Longsword",
  "Maul",
  "Morningstar",
  "Pike",
  "Rapier",
  "Scimitar",
  "Shortsword",
  "Trident",
  "Warhammer",
  "War Pick",
  "Whip",
  "Blowgun",
  "Hand Crossbow",
  "Heavy Crossbow",
  "Longbow",
  "Musket",
  "Pistol",
];

const REPUTATIONS = [
  "Admired",
  "Brutal",
  "Corrupt",
  "Disciplined",
  "Disgraced",
  "Dishonorable",
  "Elite",
  "Feared",
  "Heroic",
  "Honorable",
  "Incompetent",
  "Legendary",
  "Merciful",
  "Mixed",
  "Notorious",
  "Respected",
  "Ruthless",
  "Treacherous",
  "Trusted",
  "Unknown",
  "Unpredictable",
  "Unproven",
  "Unreliable",
];

export const MILITARY_INFO = defineFieldSet(
  [
    { key: "command", label: "Command" },
    { key: "composition", label: "Composition" },
    { key: "equipment", label: "Equipment" },
    { key: "identity", label: "Identity" },
    { key: "logistics", label: "Logistics" },
    { key: "operations", label: "Operations" },
  ],
  [
    // Command
    { key: "commandStructure", label: "Command Structure", group: "command", kind: "text", hint: "How orders flow: a single general, a council of captains, a chain of lords?" },
    { key: "commanders", label: "Commanders", group: "command", kind: "link", link: link(["character"], true), hint: "The characters in command." },
    { key: "officerPositions", label: "Officer Positions", group: "command", kind: "link", link: link(["title"], true), hint: "The ranks and offices of its officers." },
    { key: "parentFormation", label: "Parent Formation", group: "command", kind: "link", link: link(["military"]), hint: "The larger force this one belongs to." },
    {
      key: "subordinateFormations",
      label: "Subordinate Formations",
      group: "command",
      kind: "link",
      link: link(["military"], true),
      hint: "Units under its command.",
    },
    {
      key: "successionOfCommand",
      label: "Succession of Command",
      group: "command",
      kind: "text",
      hint: "Who takes over if the commander falls. Armies break when nobody knows.",
    },
    // Composition
    { key: "eliteUnits", label: "Elite Units", group: "composition", kind: "link", link: link(["military"], true), hint: "Its best units, the ones sent where it matters." },
    { key: "personnelStrength", label: "Personnel Strength", group: "composition", kind: "text", hint: "How many soldiers it fields." },
    {
      key: "recruitmentMethod",
      label: "Recruitment Method",
      group: "composition",
      kind: "select",
      multiple: true,
      options: ["Volunteer", "Conscription", "Feudal Levy", "Mercenary Contract", "Hereditary Service", "Magical Creation", "Mixed", "Other"],
      hint: "How it fills its ranks. Pick every way that applies.",
    },
    {
      key: "recruitmentRequirements",
      label: "Recruitment Requirements",
      group: "composition",
      kind: "text",
      hint: "What it takes to join: age, strength, birth, an oath?",
    },
    {
      key: "speciesRepresented",
      label: "Species Represented",
      group: "composition",
      kind: "link",
      link: link(["species"], true),
      hint: "The species serving in its ranks.",
    },
    { key: "training", label: "Training", group: "composition", kind: "text", hint: "How its soldiers are trained, and how long it takes." },
    {
      key: "unitSpecialization",
      label: "Unit Specialization",
      group: "composition",
      kind: "select",
      multiple: true,
      options: ["Infantry", "Cavalry", "Archers", "Siege", "Naval", "Aerial", "Reconnaissance", "Arcane", "Divine", "Support", "Combined Arms", "Other"],
      hint: "What its troops are trained to do. Pick every specialty that applies.",
    },
    // Equipment
    {
      key: "commonArmors",
      label: "Common Armors",
      group: "equipment",
      kind: "select",
      multiple: true,
      options: ARMORS,
      hint: "The armor its soldiers usually wear.",
    },
    {
      key: "commonWeapons",
      label: "Common Weapons",
      group: "equipment",
      kind: "select",
      multiple: true,
      options: WEAPONS,
      hint: "The weapons its soldiers usually carry.",
    },
    {
      key: "magicalCapabilities",
      label: "Magical Capabilities",
      group: "equipment",
      kind: "select",
      multiple: true,
      options: ["None", "Abjuration", "Conjuration", "Divination", "Enchantment", "Evocation", "Illusion", "Necromancy", "Transmutation"],
      hint: "The schools of magic it can bring to a battle.",
    },
    {
      key: "mountsAndWarBeasts",
      label: "Mounts and War Beasts",
      group: "equipment",
      kind: "link",
      link: link(["species"], true),
      hint: "Horses, griffons, war elephants — the creatures it rides or unleashes.",
    },
    {
      key: "signatureEquipments",
      label: "Signature Equipments",
      group: "equipment",
      kind: "link",
      link: link(["item"], true),
      hint: "Gear it's known for — the thing enemies recognize from afar.",
    },
    {
      key: "siegeEquipment",
      label: "Siege Equipment",
      group: "equipment",
      kind: "link",
      link: link(["item", "technology"], true),
      hint: "Rams, trebuchets, siege towers and stranger engines.",
    },
    {
      key: "vehiclesAndVessels",
      label: "Vehicles and Vessels",
      group: "equipment",
      kind: "link",
      link: link(["item", "technology"], true),
      hint: "Wagons, warships, airships and whatever else carries it to war.",
    },
    // Identity
    {
      key: "allegiance",
      label: "Allegiance",
      group: "identity",
      kind: "link",
      link: link(["territory", "organization", "character"], true),
      hint: "Who it serves. Loyalty can be bought, sworn or inherited.",
    },
    { key: "establishedOn", label: "Established On", group: "identity", kind: "text", hint: "When it was raised." },
    {
      key: "formationType",
      label: "Formation Type",
      group: "identity",
      kind: "select",
      multiple: true,
      options: ["Army", "Fleet", "Legion", "Regiment", "Battalion", "Company", "Squadron", "Warband", "Guard", "Other"],
      hint: "What kind of force this is.",
    },
    {
      key: "founders",
      label: "Founders",
      group: "identity",
      kind: "link",
      link: link(["character", "organization"], true),
      hint: "Who raised it.",
    },
    { key: "mottoOrBattleCry", label: "Motto or Battle Cry", group: "identity", kind: "text", hint: "What its soldiers shout as they charge." },
    {
      key: "serviceType",
      label: "Service Type",
      group: "identity",
      kind: "select",
      options: ["Standing Force", "Reserve", "Militia", "Mercenary Force", "Personal Retinue", "Irregular Force", "Other"],
      hint: "How it serves: always under arms, called up when needed, or for hire?",
    },
    {
      key: "status",
      label: "Status",
      group: "identity",
      kind: "select",
      options: ["Forming", "Active", "Inactive", "Disbanded", "Destroyed", "Unknown"],
      hint: "Whether it still exists and fights.",
    },
    // Logistics
    {
      key: "basesAndGarrisons",
      label: "Bases and Garrisons",
      group: "logistics",
      kind: "link",
      link: link(["building", "settlement"], true),
      hint: "Where it's stationed.",
    },
    { key: "fundingSources", label: "Funding Sources", group: "logistics", kind: "text", hint: "Who pays for it: the crown, taxes, plunder, a patron?" },
    { key: "medicalSupport", label: "Medical Support", group: "logistics", kind: "text", hint: "Who tends its wounded: surgeons, clerics, nobody?" },
    { key: "payAndCompensation", label: "Pay and Compensation", group: "logistics", kind: "text", hint: "What its soldiers earn. Unpaid armies rarely stay loyal." },
    {
      key: "supplySources",
      label: "Supply Sources",
      group: "logistics",
      kind: "link",
      link: link(["settlement", "territory", "organization"], true),
      hint: "Where its food, arms and horses come from.",
    },
    {
      key: "transportAndSupplyMethods",
      label: "Transport and Supply Methods",
      group: "logistics",
      kind: "text",
      hint: "How supplies reach the front: wagon trains, ships, portals, foraging?",
    },
    // Operations
    {
      key: "areasOfOperation",
      label: "Areas of Operation",
      group: "operations",
      kind: "link",
      link: link(["territory", "geography"], true),
      hint: "Where it operates.",
    },
    { key: "combatDoctrine", label: "Combat Doctrine", group: "operations", kind: "text", hint: "How it prefers to fight: shield walls, ambushes, overwhelming magic?" },
    { key: "currentObjectives", label: "Current Objectives", group: "operations", kind: "text", hint: "What it's trying to achieve right now." },
    {
      key: "deploymentStatus",
      label: "Deployment Status",
      group: "operations",
      kind: "select",
      options: ["Garrisoned", "Mobilizing", "Marching", "Deployed", "Besieging", "Besieged", "Retreating", "Demobilizing"],
      hint: "Where it stands right now.",
    },
    {
      key: "militaryAllies",
      label: "Military Allies",
      group: "operations",
      kind: "link",
      link: link(["military", "organization"], true),
      hint: "Forces and organizations that fight alongside it.",
    },
    {
      key: "militaryEnemies",
      label: "Military Enemies",
      group: "operations",
      kind: "link",
      link: link(["military", "organization"], true),
      hint: "Forces and organizations it fights against.",
    },
    {
      key: "notableCampaignsAndBattles",
      label: "Notable Campaigns and Battles",
      group: "operations",
      kind: "link",
      link: link(["generic"], true),
      hint: "The fights it's remembered for.",
    },
    {
      key: "readiness",
      label: "Readiness",
      group: "operations",
      kind: "select",
      options: ["High", "Moderate", "Low", "Nonoperational", "Unknown"],
      hint: "How ready it is to fight at a moment's notice.",
    },
    {
      key: "reputation",
      label: "Reputation",
      group: "operations",
      kind: "select",
      options: REPUTATIONS,
      hint: "How friends and foes see it.",
    },
  ]
);
