import { defineFieldSet, link } from "../info-fields";

export const TECHNOLOGY_INFO = defineFieldSet(
  [
    { key: "adoption", label: "Adoption" },
    { key: "applications", label: "Applications" },
    { key: "development", label: "Development" },
    { key: "identity", label: "Identity" },
    { key: "operation", label: "Operation" },
    { key: "production", label: "Production" },
    { key: "risksAndLimitations", label: "Risks and Limitations" },
  ],
  [
    // Adoption
    {
      key: "accessibility",
      label: "Accessibility",
      group: "adoption",
      kind: "select",
      options: ["Public Knowledge", "Professionally Restricted", "Licensed", "Secret", "Forbidden", "Lost"],
      hint: "Who is allowed to know how it works.",
    },
    {
      key: "associatedCultures",
      label: "Associated Cultures",
      group: "adoption",
      kind: "link",
      link: link(["culture"], true),
      hint: "Cultures known for using or inventing it.",
    },
    {
      key: "distribution",
      label: "Distribution",
      group: "adoption",
      kind: "select",
      options: ["Unique Prototype", "Local", "Regional", "National", "Widespread", "Unknown"],
      hint: "How far it has spread.",
    },
    { key: "legalRestrictions", label: "Legal Restrictions", group: "adoption", kind: "link", link: link(["law"], true), hint: "Laws that limit or ban it." },
    {
      key: "regionsUsed",
      label: "Regions Used",
      group: "adoption",
      kind: "link",
      link: link(["territory", "settlement"], true),
      hint: "Where it's in use.",
    },
    {
      key: "usingOrganizations",
      label: "Using Organizations",
      group: "adoption",
      kind: "link",
      link: link(["organization"], true),
      hint: "Organizations that rely on it.",
    },
    // Applications
    { key: "civilianUses", label: "Civilian Uses", group: "applications", kind: "text", hint: "What ordinary people use it for." },
    {
      key: "implementedIn",
      label: "Implemented In",
      group: "applications",
      kind: "link",
      link: link(["item", "building"], true),
      hint: "Items and buildings that use it.",
    },
    { key: "militaryUses", label: "Military Uses", group: "applications", kind: "text", hint: "How armies put it to use." },
    { key: "socialImpact", label: "Social Impact", group: "applications", kind: "text", hint: "How it changed daily life, work or power." },
    {
      key: "usingMilitaryForces",
      label: "Using Military Forces",
      group: "applications",
      kind: "link",
      link: link(["military"], true),
      hint: "Military forces that field it.",
    },
    // Development
    { key: "basedOn", label: "Based On", group: "development", kind: "link", link: link(["technology"], true), hint: "Earlier technologies it builds on." },
    {
      key: "competingTechnologies",
      label: "Competing Technologies",
      group: "development",
      kind: "link",
      link: link(["technology"], true),
      hint: "Rival approaches to the same problem.",
    },
    { key: "dateOfInvention", label: "Date of Invention", group: "development", kind: "text", hint: "When it was invented." },
    {
      key: "developmentStatus",
      label: "Development Status",
      group: "development",
      kind: "select",
      options: ["Theoretical", "Experimental", "Prototype", "Established", "Obsolete", "Lost", "Rediscovered"],
      hint: "How far along it is, from an idea on paper to a forgotten relic.",
    },
    {
      key: "inventors",
      label: "Inventors",
      group: "development",
      kind: "link",
      link: link(["character", "organization"], true),
      hint: "Who invented it.",
    },
    {
      key: "placeOfOrigin",
      label: "Place of Origin",
      group: "development",
      kind: "link",
      link: link(["settlement", "territory", "building"]),
      hint: "Where it was invented.",
    },
    { key: "replacedBy", label: "Replaced By", group: "development", kind: "link", link: link(["technology"], true), hint: "Newer technologies that made it obsolete." },
    // Identity
    {
      key: "fieldOfApplication",
      label: "Field of Application",
      group: "identity",
      kind: "select",
      multiple: true,
      options: ["Agriculture", "Construction", "Manufacturing", "Medicine", "Transportation", "Communication", "Warfare", "Navigation", "Energy", "Magic", "Other"],
      hint: "The areas it's used in. Pick every field that applies.",
    },
    {
      key: "technologyType",
      label: "Technology Type",
      group: "identity",
      kind: "select",
      multiple: true,
      options: ["Device Design", "Machine", "Infrastructure System", "Production Process", "Practical Technique", "Material Innovation", "Other"],
      hint: "What kind of technology this is.",
    },
    // Operation
    { key: "operatingPrinciples", label: "Operating Principles", group: "operation", kind: "text", hint: "How it works, in a sentence or two." },
    {
      key: "operatingRequirements",
      label: "Operating Requirements",
      group: "operation",
      kind: "text",
      hint: "What it needs to run: fuel, crew, calm weather, a full moon?",
    },
    {
      key: "powerSource",
      label: "Power Source",
      group: "operation",
      kind: "select",
      multiple: true,
      options: ["Human Labor", "Animal Labor", "Water", "Wind", "Heat", "Chemical", "Electrical", "Magical", "Mixed", "Other"],
      hint: "What drives it. Pick every source that applies.",
    },
    { key: "requiredExpertise", label: "Required Expertise", group: "operation", kind: "text", hint: "The skills needed to operate it." },
    { key: "requiredMagic", label: "Required Magic", group: "operation", kind: "link", link: link(["magic"], true), hint: "Spells or magic it depends on." },
    {
      key: "requiredTechnologies",
      label: "Required Technologies",
      group: "operation",
      kind: "link",
      link: link(["technology"], true),
      hint: "Other technologies it can't work without.",
    },
    {
      key: "technicalDocumentation",
      label: "Technical Documentation",
      group: "operation",
      kind: "link",
      link: link(["document"], true),
      hint: "Manuals, schematics and notes describing it.",
    },
    // Production
    { key: "byproducts", label: "Byproducts", group: "production", kind: "text", hint: "What it leaves behind: smoke, slag, waste, residue?" },
    {
      key: "manufacturers",
      label: "Manufacturers",
      group: "production",
      kind: "link",
      link: link(["organization", "character"], true),
      hint: "Who builds it.",
    },
    { key: "productionCost", label: "Production Cost", group: "production", kind: "text", hint: "What it costs to make." },
    {
      key: "productionFacilities",
      label: "Production Facilities",
      group: "production",
      kind: "link",
      link: link(["building"], true),
      hint: "Workshops and foundries where it's made.",
    },
    { key: "productionTime", label: "Production Time", group: "production", kind: "text", hint: "How long it takes to make one." },
    { key: "requiredMaterials", label: "Required Materials", group: "production", kind: "text", hint: "What it's made from." },
    { key: "requiredTools", label: "Required Tools", group: "production", kind: "text", hint: "The tools needed to build it." },
    { key: "resultingProducts", label: "Resulting Products", group: "production", kind: "text", hint: "What it produces." },
    // Risks and Limitations
    {
      key: "environmentalEffects",
      label: "Environmental Effects",
      group: "risksAndLimitations",
      kind: "text",
      hint: "What it does to the land, water and air around it.",
    },
    { key: "failureModes", label: "Failure Modes", group: "risksAndLimitations", kind: "text", hint: "How it breaks — and what happens when it does." },
    { key: "knownLimitations", label: "Known Limitations", group: "risksAndLimitations", kind: "text", hint: "What it can't do." },
    {
      key: "maintenanceRequirements",
      label: "Maintenance Requirements",
      group: "risksAndLimitations",
      kind: "text",
      hint: "The upkeep it needs to keep working.",
    },
    { key: "safetyHazards", label: "Safety Hazards", group: "risksAndLimitations", kind: "text", hint: "The dangers to whoever uses it." },
    { key: "vulnerabilities", label: "Vulnerabilities", group: "risksAndLimitations", kind: "text", hint: "How an enemy could sabotage or exploit it." },
  ]
);
